### ISSUE TITLE
If the object queries pretraining weight is loaded, will the training time be reduced?

### ISSUE THREAD

**Issue by tfygg** [facebookresearch/detr#102]
If the object queries pretraining weight is loaded, will the training time be reduced?

**Comment by alcinos** [comment]
Hi,
I'm am not entirely clear on what you want to transfer, is it only the box embedding?
https://github.com/facebookresearch/detr/blob/10a2c759454930813aeac7af5e779f835dcb75f5/models/detr.py#L39

If yes, I wouldn't really expect it to significantly speedup training, but that being said we never tried it so feel free to give it a go and report your findings.

**Comment by fmassa** [comment]
Following @alcinos question, I'm closing this issue, but please let us know if you have further questions or findings.

**Comment by tfygg** [comment]
> Hi,
> I'm am not entirely clear on what you want to transfer, is it only the box embedding?
> https://github.com/facebookresearch/detr/blob/10a2c759454930813aeac7af5e779f835dcb75f5/models/detr.py#L39
> 
> If yes, I wouldn't really expect it to significantly speedup training, but that being said we never tried it so feel free to give it a go and report your findings.

Object queries look like learned anchor. 
But I only have two 2080Ti, so I could not try.
