### ISSUE TITLE
What's the consideration of not apply positional encoding for V at the self-attention layer?

### ISSUE THREAD

**Issue by you4ever** [facebookresearch/detr#105]
Question: What's the consideration of not apply positional encoding for V at the self-attention layer? 

```
def forward_post(self, 
                     src, 
                     src_mask: Optional[Tensor] = None,
                     src_key_padding_mask: Optional[Tensor] = None,
                     pos: Optional[Tensor] = None):

        q = k = self.with_pos_embed(src, pos)
        src2 = self.self_attn(q, k, value=src, attn_mask=src_mask,
                              key_padding_mask=src_key_padding_mask)[0]
```

**Comment by szagoruyko** [comment]
Hi, we follow the standard practice, see Transformer XL or Stand-alone self-attention in vision, in adding positional encoding to queries and keys only, except in our case it is absolute and not relative.

**Comment by fmassa** [comment]
Following @szagoruyko answer, I'm closing this issue, but please let us know if you have further questions

**Comment by wwdok** [comment]
@szagoruyko @you4ever @fmassa @valencebond
I still can not understand why, I looked the [ViT code](https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/vit.py), but found it still apply positional encoding to all of QKV, could anyone explain it more detailed ? Maybe put some link, thanks in advance !

**Comment by alexzeng1206** [comment]
+1. I have read the code and find that although the positional encoding is added within q and k during the computation of self/cross-attention, the features are just obtained from v (only contain appearance feature without positional encoding) throughout the process, so I don't know why the final output slot contains spatial information that allows the FFN to predict the bounding box based on it. Can anyone help to explain where such spatial information comes from?

**Comment by hkproj** [comment]
Hi @wwdok @diPDew and @wenzhengzeng my explanation here on the reasons behind this choice: https://github.com/facebookresearch/detr/issues/415#issuecomment-1684905352
