### ISSUE TITLE
Questions about spatial positional encoding and queries

### ISSUE THREAD

**Issue by Jacobew** [facebookresearch/detr#107]
Hi, is there any reason for not adding spatial positional encoding to V in both encoder and decoder? This is different from the original transformer implementation and I found no ablation studies in this paper. 

Another question about the terms _queries_ and _object queries_ in A.3:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/26053586/85867401-6bb63900-b7fb-11ea-922f-96c1c3939150.png">
I found the corresponding variables named tgt [here](https://github.com/facebookresearch/detr/blob/10a2c759454930813aeac7af5e779f835dcb75f5/models/transformer.py#L55) and query_embed [here](https://github.com/facebookresearch/detr/blob/10a2c759454930813aeac7af5e779f835dcb75f5/models/detr.py#L39). 
I am a little confused by these two terms and their functional differences. 
I guess one of them is similar to the spatial positional encoding but is learned since the order of queries is not defined and the other one is expected to be the Q in the decoder. 
But these two variables have the same dimension and are both learned via backpropagation and I wonder what they have learned after training? Is it possible to remove any of them?

I am also curious about the results of prenorm transformer (pre_norm is set false in all experiments). It seems this one is easier to optimize compared to postnorm transformer.

**Comment by szagoruyko** [comment]
> I am a little confused by these two terms and their functional differences.

we refer to activations coming out of each decoder layer as queries, and to positional encodings as object queries, such that queries change with decoder layers, and object queries do not change and are shared across all decoder layers. Sorry for the slightly confusing terminology.

> I am also curious about the results of prenorm transformer (pre_norm is set false in all experiments). It seems this one is easier to optimize compared to postnorm transformer.

we get slightly lower AP with pre-norm transformer, but it is true that it is easier to optimize.

**Comment by fmassa** [comment]
Following @szagoruyko answer, I'm closing this issue but please let us know if you have any other questions

**Comment by XuyangBai** [comment]
Hi, I also have a question regarding the queries and object queries. When I first read DETR, I thought the `learned object queries` is the Query for transformer decoder (or named `tgt` in your repo) and there is no positional encoding for Query. But I find for your implementation the `tgt` is zeros and the positional encoding is the `learnable object queries`.  Is it on prupose or the former one is also OK?
