### ISSUE TITLE
How to calculate flops

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/detr#110]
Hi! thanks for sharing the wonderful work, I'm wondering how to evaluate the flops of DETR model, could you pls include a python script?

**Comment by fmassa** [comment]
Hi,

As we mentioned in the "FLOPS computation" section of the paper, we compute the FLOPS with the tool `flop_count_operators` from Detectron2 over the first 100 images of COCO val2017, modifying it slightly to take `bmm` into account.

Here is a gist containing the code to reproduce the results we report in the paper. You should put those 3 files in the root of `detr`, and modify it to point to the location of your COCO dataset. 

https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c

<details>
<summary>
Here is the result I obtain from running `compute_flops`, on a P100 GPU:
</summary>

```python
~/github/detr$ python compute_flops.py
loading annotations into memory...
Done (t=0.49s)
creating index...
index created!
Using cache found in /private/home/fmassa/.cache/torch/hub/facebookresearch_detr_master
  0%|                                                                                                                                          | 0/100 [00:00<?, ?it/s]/private/home/fmassa/.conda/envs/segmentation/lib/python3.7/site-packages/torch/tensor.py:455: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/private/home/fmassa/github/detr/util/misc.py:296: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)
/private/home/fmassa/github/detr/util/misc.py:297: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  m[: img.shape[1], :img.shape[2]] = False
WARNING:root:Skipped operation aten::ones 1 time(s)
WARNING:root:Skipped operation aten::max_pool2d 1 time(s)
WARNING:root:Skipped operation aten::upsample_nearest2d 1 time(s)
WARNING:root:Skipped operation aten::bitwise_not 1 time(s)
WARNING:root:Skipped operation aten::cumsum 2 time(s)
WARNING:root:Skipped operation aten::pow 1 time(s)
WARNING:root:Skipped operation aten::sin 2 time(s)
WARNING:root:Skipped operation aten::cos 2 time(s)
WARNING:root:Skipped operation aten::stack 3 time(s)
WARNING:root:Skipped operation aten::repeat 1 time(s)
WARNING:root:Skipped operation aten::masked_fill 12 time(s)
WARNING:root:Skipped operation aten::layer_norm 36 time(s)
WARNING:root:Skipped operation aten::sigmoid 1 time(s)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:42<00:00,  1.59s/it]
=============================

detr_resnet50
  flops : (85.51592294544001, 9.59742021757218, 60.808601102, 102.789376419)
  time : (0.059102573633193975, 0.005186571410399482, 0.04723012447357178, 0.06860597133636474)
```

</details>
Which returns an average flops for DETR ResNet50 of 85.51592294544001.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions

**Comment by twangnh** [comment]
@fmassa , Thank you. I get same result for flops and similar result for time, but the time is 0.059102573633193975 s for a single image, so the FPS should be 1/0.059102573633193975, that is about 17 FPS?

**Comment by fmassa** [comment]
@twangnh yes, the FPS should be about 17 for a P100 GPU without optimizations torchscript.

What we did in the paper, and we mention in the captions of Table 1 in the paper, is that we evaluate for both Faster R-CNN and DETR with torchscript optimizations, and we execute the models on a V100 GPU.

Here is what you obtain if you run the code on a V100 GPU, without modifications:
```
detr_resnet50
  flops : (85.51592294544001, 9.59742021757218, 60.808601102, 102.789376419)
  time : (0.04236030936241149, 0.0031254237510941886, 0.034110498428344724, 0.04882349967956543)
```
which corresponds to ~24 FPS.

Now if you add the following line to the script, just after converting it to cuda:
```python
model.transformer = torch.jit.script(transformer)
```
you'll be performing some optimizations for the transformer model, which is not really very optimized in PyTorch for now, and has a lot of synchronization points. With torchscript you'll get the following runtimes:
```
detr_resnet50
  flops : (0.0, 0.0, 0, 0)
  time : (0.03614641046524048, 0.002810349883302843, 0.02816600799560547, 0.04131600856781006)
```
which gives an FPS of ~28, on par with what we report on the paper. Notice that I disabled flop computation to get results quicker.

Let us know if you have further questions

**Comment by twangnh** [comment]
@fmassa thanks very much for the detailed reply!

**Comment by Patrickctyyx** [comment]
> Let us know if you have further quest

Hello, I wonder what is the `transformer` in `torch.jit.script(transformer)`, is it `torch.nn.modules.transformer`? Thanks very much

**Comment by ilem777** [comment]
@fmassa @twangnh Hello, how can I run the `computer_flops.py`file?
I changed PATH_TO_COCO in line 52 to my custom dataset path.
Then I run it, why does it automatically download a model to test it?
I think I should change lines 59~63
```
device = torch.device('cuda')
results = {}
for model_name in ['detr_resnet50']:
    model = torch.hub.load('facebookresearch/detr', model_name, pretrained=True)
    model.to(device)
```
How can I modify these lines to read my trained model? The path of my trained model is in `outputs/checkpint.pth`. Thank you, this is really bothering me.
