### ISSUE TITLE
Visualization of all box predictions

### ISSUE THREAD

**Issue by Jacobew** [facebookresearch/detr#113]
Hi, can you share the script for generating Fig.7? I think this may help a lot in understanding the behavior of detr. :) 
Thanks in advance!

**Comment by fmassa** [comment]
Hi,

Thanks for your interest in DETR.

Here is a gist that generates the figure 7 in the paper https://gist.github.com/fmassa/d443b1fdca2a5d5debca902218f3232b
Note that the image is not exactly the same, as for the paper we used a slightly different model as the one available on TorchHub.

You need to put this script in the root folder of DETR github repo, as it calls into a couple of functions in the repo (namely for loading the COCO dataset). You also need to change the path to point to your COCO dataset location.

This is the image that I get after running `python query_distribution.py`:
![image](https://user-images.githubusercontent.com/9110200/85952650-0ed99080-b96b-11ea-92ef-1ad6ff44a778.png)

This code generates a `png` file named `query_distribution.png` in the root folder.

I believe I've answered your question, so I'm closing the issue, but let us know if you have further questions.
