### ISSUE TITLE
DETR Detectron2 Wrapper Errors

### ISSUE THREAD

**Issue by dsshean** [facebookresearch/detr#118]
Latest Code pull with D2 wrapper.

    transformer = Transformer(
**TypeError: __init__() got an unexpected keyword argument 'pass_pos_and_query'**

From Transformer:

class Transformer(nn.Module):

    def __init__(self, d_model=512, nhead=8, num_encoder_layers=6,
                 num_decoder_layers=6, dim_feedforward=2048, dropout=0.1,
                 activation="relu", normalize_before=False,
                 return_intermediate_dec=False):

no pass_poss_and_query.  I gather its a bool from config.py
    cfg.MODEL.DETR.PASS_POS_AND_QUERY = True

Tried searching entire repo, no reference for pass_poss_and_query besides the config and detr.py from D2.  Thanks

**Comment by alcinos** [comment]
Hi @dsshean 
Thanks for reporting. This should be fixed on master now, sorry for the inconvenience.
Don't hesitate to reach out if you have any other issue/question.
