### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by ggeo** [facebookresearch/detr#12]
Hi and thanks for the code!
When I try to load detr it gives : 

`from detr.models import detr`
```

 7 from torch import nn
      8 
----> 9 from util import box_ops
     10 from util.misc import (NestedTensor, accuracy, get_world_size, interpolate,
     11                        is_dist_avail_and_initialized)

ModuleNotFoundError: No module named 'util'
```

or

`from detr.engine import evaluate`

```
10 import torch
     11 
---> 12 import util.misc as utils
     13 from datasets.coco_eval import CocoEvaluator
     14 from datasets.panoptic_eval import PanopticEvaluator

ModuleNotFoundError: No module named 'util'
```

**Comment by fmassa** [comment]
Hi,

You need to be in the root folder of the github repo to be able to import it -- we haven't packaged DETR as a library.

So make sure that you are in the root folder (where `main.py` is) before trying to import `detr.models`.

I believe this should fix your issue and as such I'm closing the issue, but please let us know if this isn't the case.

**Comment by ggeo** [comment]
Oh, sorry I didn't pay attention.

It runs fine now, thanks!
