### ISSUE TITLE
mix precision training?

### ISSUE THREAD

**Issue by Jacobew** [facebookresearch/detr#127]
Hi, do you have any plan to support mix precision training of detr? 
Since the training schedule is too long and I believe this feature may be a workaround.
If not, I'll really appreciate it if you can give me some advice to achieve this. Thanks! :)

**Comment by szagoruyko** [comment]
Hi, we briefly gave apex amp a quick try and saw a significant AP drop, without much improvement in speed on V100. It is true that figuring out the bottlenecks (eg transformer blocks are inefficient in pytorch) and the reason for the drop in AP would be great, and would allow much faster training potentially.

**Comment by alcinos** [comment]
I believe the question has been answered, closing this.
Feel free to reach out if you have further concern.

**Comment by Jacobew** [comment]
@szagoruyko  Hi, can you share your mix precision training code? I would like to try it myself. Many Thanks! :)

**Comment by Jacobew** [comment]
I've made some preliminary attempts on applying native apex to DETR and encountered some errors. See [here](https://discuss.pytorch.org/t/applying-apex-amp-to-detr/86984/8?u=jacobew). Still struggling to figure it out and hope to get some help.

**Comment by szagoruyko** [comment]
@Jacobew not many changes:
* add 
```python
model, optimizer = apex.amp.initialize(model, optimizer, opt_level='O2')
```
* move DDP construction after this line
* add loss scaling
```python
with amp.scale_loss(losses, optimizer) as scaled_loss:
            scaled_loss.backward()
```

should be done, this way the model is forwarded in fp16, and the loss is still computed in fp32 for stability
perhaps also use apex fp16 attention for speed

**Comment by Jacobew** [comment]
@szagoruyko  With this change a Runtime Error occurs:
```
RuntimeError: "cdist_cuda" not implemented for 'Half'
```
It seems that torch.cdist is not working with half precision. More details [here](https://discuss.pytorch.org/t/applying-apex-amp-to-detr/86984/3). 
I’ve tried decorating SetCriterion.foward() with amp.float_function but the errors remain. 
I wonder if this is due to different pytorch/apex versions? 
I'm working on pytorch 1.4.0.

**Comment by szagoruyko** [comment]
looks like you are trying to run criterion in fp16, I think it should be in fp32

**Comment by Jacobew** [comment]
I run criterion in fp16 since the RuntimeError occurs in the forward step of setcriterion. 
```
Traceback (most recent call last):
  File "main_apex.py", line 269, in <module>
    main(args)
  File "main_apex.py", line 219, in main
    args.clip_max_norm)
  File "/home/detr/engine_apex.py", line 37, in train_one_epoch
    loss_dict = criterion(outputs, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/detr/models/detr.py", line 225, in forward
    indices = self.matcher(outputs_without_aux, targets)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/detr/models/matcher.py", line 71, in forward
    cost_bbox = torch.cdist(out_bbox, tgt_bbox, p=1)
  File "/usr/local/lib/python3.7/dist-packages/torch/functional.py", line 732, in cdist
    return _VF.cdist(x1, x2, p, None)
RuntimeError: "cdist_cuda" not implemented for 'Half'
```
Adding @amp.float_function doesn't work here and the error remains still.

**Comment by Jacobew** [comment]
Have you tried running DETR at O1 level?

**Comment by Jacobew** [comment]
Not yet. Neither nvidia apex described by @szagoruyko and Pytorch new AMP feature work for me. 
@fmassa Can you shed some light on this? :)

**Comment by fmassa** [comment]
I never tried using amp with DETR, but I would maybe cast the output to float before feeding it to the loss

**Comment by nicolasugrinovic** [comment]
@Jacobew were you able to use AMP and solve the issues you encountered when adding native apex to DETR?

**Comment by nicolasugrinovic** [comment]
@szagoruyko Thank you for the answers in this issue. I have tried to train DETR with native AMP with torch 1.7 on RTX-2080 and just as you say, cannot see improvement in speed.  However, I don't get why there would **not be** a significant speed-up for training in **Tensor Core** enabled GPUs. After all, they do advertise that one advantage is being able to train Transformers faster.

**Comment by gautamsreekumar** [comment]
@nicolasugrinovic Thank you for the earlier comment. Could you please share how you solved the error regarding ```torch.cdist``` while using AMP/Apex?
