### ISSUE TITLE
Quick question about training DC5 models

### ISSUE THREAD

**Issue by thangvubk** [facebookresearch/detr#129]
In this [gist](https://gist.github.com/szagoruyko/9c9ebb8455610958f7deaa27845d7918) the DC5 model is trained with multiple machines.
If I have only one machine with 8 GPUs, can I simply train the DC5 model by changing batch_size to 1 and setting dilation to get the expected result with 300 epoch schedule?
``python -m torch.distributed.launch --nproc_per_node=8 --batch_size 1 --dilation --use_env main.py --coco_path``

**Comment by fmassa** [comment]
Hi,

The models that we provide were trained on 500 epochs.
The problem with DC5 models is that they require a lot of memory, so even with a batch size of 1 you might need to use more than 16GB of GPU memory for it to fit, and it would take a very long time to train.

We would expect that training with 1 node should work, although we are investigating some weird behaviors in https://github.com/facebookresearch/detr/issues/115 , where the user reported being able to reproduce the expected results, but the training curves were a bit different in the end.

I believe I have answered your question, and as such I'm closing this issue, but let us know if you have further questions
