### ISSUE TITLE
something wrong with code in the paper

### ISSUE THREAD

**Issue by qianjinhao** [facebookresearch/detr#130]
inputs = torch.randn(1, 3, 800, 1200)
when i change the code to:
inputs = torch.randn(2, 3, 800, 1200)
it gets wrong with the output:
RuntimeError: the batch number of src and tgt must be equal
I think this number is batchsize,  Did I get it wrong?

**Comment by alcinos** [comment]
Hi @qianjinhao
Thanks for your interest in DETR. 
I assume you are talking about the demo code we provide in appendix of the paper (also featured in our [Standalone Colab Notebook](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_demo.ipynb) As we state in the paper "Note that it does not support batching, hence it is suitable only for inference or training with DistributedDataParallel with one image per GPU"

If you want to use a higher batchsize, you must use the full model that is available in this repo.
I believe I have answered your question, and as such I'm closing this. If you have further concerns, feel free to reach out.

**Comment by qianjinhao** [comment]
> Hi @qianjinhao
> Thanks for your interest in DETR.
> I assume you are talking about the demo code we provide in appendix of the paper (also featured in our [Standalone Colab Notebook](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_demo.ipynb)). As we state in the paper "Note that it does not support batching, hence it is suitable only for inference or training with DistributedDataParallel with one image per GPU"
> 
> If you want to use a higher batchsize, you must use the full model that is available in this repo.
> I believe I have answered your question, and as such I'm closing this. If you have further concerns, feel free to reach out.

thankyou!
