### ISSUE TITLE
Input type of Detectron2 DETR

### ISSUE THREAD

**Issue by jd730** [facebookresearch/detr#136]
Hi,

I just tried to use Detectron2 wrapped DETR and found that the input of the backbone network is `NestedTensor` not `ImageList`.

As a result, L46-48 yield errors (I manually changed L46 from `image.tensor` to `image.tensors` as shown in #135).

Is it a bug of the wrapper or do I miss something?

Thank you.

I ran `python train_net.py --config configs/detr_256_6_6_torchvision.yaml --num-gpus 8` in d2 folder.

![image](https://user-images.githubusercontent.com/9247850/86525853-3aa6ca00-bec7-11ea-817e-58a775b4984b.png)

**Comment by alcinos** [comment]
Hi @jd730 
I can't reproduce your issue. Can you confirm you are on latest master? Maybe your D2 is too old?
As for the type, I believe you are referring to this annotation:
https://github.com/facebookresearch/detr/blob/ae03a2d6e52a9ec1b67f85437d0a275c5abbe9ac/models/detr.py#L44
It is true that "normal" DETR will expect NestedTensor (IIRC the type annotation is required for scripting), however, when using D2, this input will NOT be a NestedTensor. If you check the call stack, the images come from `preprocess_image`
https://github.com/facebookresearch/detr/blob/ae03a2d6e52a9ec1b67f85437d0a275c5abbe9ac/d2/detr/detr.py#L154-L155
and this function returns an ImageList:
https://github.com/facebookresearch/detr/blob/ae03a2d6e52a9ec1b67f85437d0a275c5abbe9ac/d2/detr/detr.py#L222-L228

You should track where your NestedTensor comes from, but this should not happen normally.
Best of luck

**Comment by jd730** [comment]
Hi @alcinos, Thank you for your kind comment.
I found that I changed below wrong (add `not` in front of `isinstance`) which caused the problem.
https://github.com/facebookresearch/detr/blob/ae03a2d6e52a9ec1b67f85437d0a275c5abbe9ac/models/detr.py#L59

Thank you.
