### ISSUE TITLE
DC5 model with batch size 2

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/detr#138]
As noted in the readme, DC5 models are trained with batch size 1, but how about training with the same setting as without the dilation model? can we still observe the improvement pattern of Table 1 ?

**Comment by alcinos** [comment]
2 images per card doesn't fit with DC5 on a 16GB card, so we opted for 1 image per card. We kept the global batchsize constant at 64 by doubling the number of nodes (ie 64 cards).
For the default model (without DC5), we generally observe that it's slightly better to train with 2 img/card on 32 cards than 1 img/card on 64 cards. Similarly, if you somehow manage to train DC5 with 2 img/card on 32 cards (might be possible on 32 gb Voltas), I'd expect to be slightly better than what we report.

I think I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
