### ISSUE TITLE
Ablation study on number of attention head 

### ISSUE THREAD

**Issue by twangnh** [facebookresearch/detr#139]
Hi! thanks for sharing the wonderful work! I'm wondering if you have done an ablation study on varying the attention head number (default is 8)?

**Comment by fmassa** [comment]
Hi,

We did some preliminary experiments in the past, and we noticed that using fewer than 8 heads decreased mAP by up to 3 points on a 300-epoch schedule (if using 1 single head). After 8 heads performance plateau and didn't improve.

I believe I have answered your question, and as such I'm closing this issue, but let us know if you have further questions.
