### ISSUE TITLE
Changes for training on custom dataset

### ISSUE THREAD

**Issue by EmmanouelP** [facebookresearch/detr#141]
I've read the several issues regarding how to train your own DETR model on a custom dataset but the specific code changes are still of a mystery to me. My images and my annotations have the same structure as the coco dataset. What other changes should i make in the code in order NOT to train with the default coco dataset parameters? My dataset consists of ~8k and number of classes is 3.  Sorry if my question is somewhat trivial. Thanks in advance.

**Comment by woctezuma** [comment]
Based on #9, it is recommended to fine-tune instead if your dataset has [less than 10k images](https://github.com/facebookresearch/detr/issues/9#issuecomment-635357693).

Code for fine-tuning is mentioned [here](https://github.com/facebookresearch/detr/issues/9#issuecomment-639679284), with a link to [this Gist page](https://gist.github.com/mlk1337/651297e28199b4bb7907fc413c49f58f).
