### ISSUE TITLE
Problem in loading panoptic models from hubconf.py

### ISSUE THREAD

**Issue by yaeldekel** [facebookresearch/detr#142]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
    torch.hub.load('facebookresearch/detr', 'detr_resnet50_dc5_panoptic', pretrained=True)
```
2. what exact command you run:
3. what you observed (including __full logs__):
```
RuntimeError: Error(s) in loading state_dict for DETRsegm:
        size mismatch for detr.class_embed.weight: copying a param with shape torch.Size([251, 256]) from checkpoint, the shape in current model is torch.Size([92, 256]).
        size mismatch for detr.class_embed.bias: copying a param with shape torch.Size([251]) from checkpoint, the shape in current model is torch.Size([92]).
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.
No additional resources required.

## Expected behavior:
Expected the model to load with the correct default number of classes (default should be 250 instead of 91).

**Comment by fmassa** [comment]
Thanks for opening the issue!

We just sent a fix for it in https://github.com/facebookresearch/detr/pull/143, which just got merged.
