### ISSUE TITLE
Panoptic Segmentation via Detectron2 Wrapper

### ISSUE THREAD

**Issue by jd730** [facebookresearch/detr#144]
Hi,

Current Detectron2 Wrapper seems to focus only on the detection task. Is there any plan for integrating Panoptic segmentation, i.e. generate merged annotations (not `coco_2017_*_panoptic_separated`), add segmentation options with segmentation head?

Thank you.

**Comment by alcinos** [comment]
Hi @jd730 
Currently no one is working on this as far as I know, but we would happily merge a PR if you happen to submit one.

**Comment by jd730** [comment]
Hi @alcinos,
Thank you for your reply. I implemented for instance segmentation part but I did not expand to panoptic segmentation. I will submit PR as soon as possible.

**Comment by jd730** [comment]
Hi, @alcinos, I made PR for instance segmentation. Currently, it does not support panoptic segmentation.
