### ISSUE TITLE
Proposing bounding boxes to the panoptic head

### ISSUE THREAD

**Issue by rllin** [facebookresearch/detr#146]
My goal is to propose high-quality bounding boxes to DETR's panoptic head to get out segmentation masks

1. the panoptic head uses box embedding fed to it from the decoder
2. the actual bounding boxes are created by taking the same box embedding and passing it thru a FFN
3. this FFN is not invertible (has a relu activation term)

I wish to be able to convert a bounding box to a box embedding, and pass this thru to the panoptic head, however (as stated above) the FFN is not invertible, so I can't go from bbox -> box embedding.

Is anybody able to think of a creative way to do this?

**Comment by rllin** [comment]
thinking more about this, it would not make sense.

the box embedding are more than just representations of the bbox itself, but also of the instance and semantics in the panoptic case.

even if it was invertible, I would only get embeddings that represent only the bbox which would be incomprehensible to the panoptic head

but I'm very open to clever ideas for hacking the panoptic head for masking purposes!

**Comment by alcinos** [comment]
Hi @rllin 
Thank you for your interest in DETR.

I am not too sure what you are trying to achieve here. What do you mean exactly by "hacking the panoptic head for masking purposes"? Are you trying to do instance segmentation or something? Note that we do compute segmentation AP.

**Comment by rllin** [comment]
thanks for the response @alcinos

my goal is to inject human bounding box suggestions to produce instance segmentation masks.

it looks like tho that the panoptic head interprets box embeddings which are more than just a representation of the coordinates but also of what is inside of them.  the actual bounding box predictions are a softmax over the embeddings to achieve the coordinates by themselves.  so i'm not sure that my idea will work.

**Comment by alcinos** [comment]
Detr will produce instance segmentation masks for the objects it detects. If you're planning to try to make it generate segmentation masks for objects it doesn't know how to detect, it is very unlikely to work. If you want to detect an object from the coco category, you could simply take your human bounding box, compute the closest box amongst the 100 boxes that Detr predicts, and use the corresponding embedding for the prediction.

As you noted, the embeddings have a much stronger information content than just mere class and bounding box information. In particular, if you look at the segmentation head, the first block is a multi-head attention module. For this to do anything sensible, it requires that the box embedding of the object you are trying to segment has a high cosine similarity with the embeddings of the image features corresponding to this object (up to the linear projection that happens in the head). This will ensure that the attention focuses on the part of the image that correspond to the object at hand, and this will correspond to a sort of rough segmentation of the object, which is then refined by the convolutional part to generate the sharp mask.

Hope this helps.
