### ISSUE TITLE
Need for Speed

### ISSUE THREAD

**Issue by cbasavaraj** [facebookresearch/detr#15]
Hi, just a question on speed. The reported inference speeds are on which GPU? Tesla V100 or something less powerful? Thanks

**Comment by fmassa** [comment]
Hi,

The inference speeds are reported on a V100 GPU, using the first 100 images of COCO val2017, with min_size 800 and max_size 1333. The same applies for the FLOPS computation.

I believe I've answered your question and as such I'm closing the issue, but let us know if you have further questions!
