### ISSUE TITLE
FineTuning with similar format dataset as coco but different classes

### ISSUE THREAD

**Issue by Naivepro1990** [facebookresearch/detr#153]
Hi,

I want to fine DETR with data similar in format as mscoco but the number of classes as different. I have only 6 classes. 

Firstly, Where I need minimum changes in DETR code such as the change in the last layer to predict the number of classes and use the pretrained weights.

Secondly, the number of classes will be 6 or 7 i.e. 6 classes and 1 background.

Regards,

**Comment by mlk1337** [comment]
Hello, please take a look at the following links for information.
[https://github.com/facebookresearch/detr/issues/9](https://github.com/facebookresearch/detr/issues/9)
[https://gist.github.com/mlk1337/651297e28199b4bb7907fc413c49f58f](https://gist.github.com/mlk1337/651297e28199b4bb7907fc413c49f58f)
[https://www.kaggle.com/tanulsingh077/end-to-end-object-detection-with-transformers-detr](https://www.kaggle.com/tanulsingh077/end-to-end-object-detection-with-transformers-detr)
These links should include plenty of examples for training on custom data.
Regards

**Comment by alcinos** [comment]
Hello @Naivepro1990 
In addition to @mlk1337 's ressources, I encourage you to checkout #9, #152  and #125 
Feel free to ask questions there if you are still stuck.
Best of luck.
