### ISSUE TITLE
pad the ground truth with ∅

### ISSUE THREAD

**Issue by aliamiri1380** [facebookresearch/detr#155]
Hi,
I was reading the paper and matching it with codes and I found that
in the paper at section 3.1 authors said "we consider y also as a set of size N padded with ∅ (no object)" but our ground-truth shape is different and is not padded by N

**Comment by alcinos** [comment]
Hi @aliamiri1380 
Thank you for your interest in DETR.

As you noted, we don't explicitly pad the ground-truth with no-object, instead we rely on the fact that scipy's hungarian algorithm supports non-square cost matrices. This is exactly equivalent to padding the ground-truth with no-object and setting a cost to +infinity to these no-objects. See the documentation https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html for more information.

I believe I have answered your question, and as such I'm closing this. If you have further concerns, feel free to reach out.
