### ISSUE TITLE
AccessDenied when downloading panoptic models

### ISSUE THREAD

**Issue by SharifElfouly** [facebookresearch/detr#16]
I get an AccessDenied Error when I try to download the panoptic model .pth files linked in the readme. Url for normal models work fine.

**Comment by fmassa** [comment]
Thanks for reporting this issue! We are looking into it.

Can you let us know if you get `AccessDenied` error when running on colab or on your local machine?

**Comment by szagoruyko** [comment]
should be fixed via #18, let us know if you still have issues accessing the models.

**Comment by SharifElfouly** [comment]
Awesome, this works now!

Are you planning to publish the panoptic models via torch.hub?

**Comment by fmassa** [comment]
@SharifElfouly yes, it's on the plans
