### ISSUE TITLE
Is there any reason that DETR only predicts bounding boxes instead of directly predicting instance masks? 

### ISSUE THREAD

**Issue by JrPeng** [facebookresearch/detr#160]
FYI

**Comment by alcinos** [comment]
Hi @JrPeng 
Thank you for your interest in DETR.

In theory, it could be possible to predict masks directly. In practice though, it would likely be really costly. The training of DETR involves, amongst other things, computing a hungarian assignment between predictions and ground truth targets. If DETR operates mainly with boxes, computing the cost matrix is quite cheap (it's simply a L1 distance between boxes, or a pair-wise GIOU). If you want to predict masks exclusively, then you need to compute some kind of cost between each pair of (full-resolution) masks, and this is likely going to be too slow/memory intensive.

So, if it is possible, I believe it will not be straightforward, at least given current hardware capabilities.

I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
