### ISSUE TITLE
"Multiple detections" problem during inference

### ISSUE THREAD

**Issue by jeromen7** [facebookresearch/detr#174]
Hello,

I imported a pre-trained model and trained it with my own dataset with these commands for the import :

`#!wget https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth`
`checkpoint=torch.load("detr-r50-e632da11.pth",map_location='cpu')`
`del checkpoint["model"]["class_embed.weight"]`
`del checkpoint["model"]["class_embed.bias"]`
`torch.save(checkpoint,"test_logo.pth")`

The model works pretty well but the problem is that sometimes it detects multiple bounding boxes for the same object and I don't know how to correct it ...
Here are some examples (for your understanding, the model is trained to detect logos like Airbus, or Peugeot) :

![image](https://user-images.githubusercontent.com/45367085/89157689-37a60480-d56d-11ea-90eb-281b2bd734b8.png)
![image](https://user-images.githubusercontent.com/45367085/89157827-6c19c080-d56d-11ea-9095-e3d041d9a977.png)
![image](https://user-images.githubusercontent.com/45367085/89157859-79cf4600-d56d-11ea-95d4-3b2b4e050ba4.png)

Shouldn't it keep only the box with the higher score ? And so avoid the multiple detections ?

Does this problem comes from the fact that the `num_queries` is set to 100 in the downloaded pretrained model ? My dataset only contains up to 20 logos per image maximum, so maybe `num_queries` is too high and it forces the model to detect more objects than it should ..?
But if I change the `num_queries` when I make the training I have a dimension error so I don't know how to change the `num_queries` for my model anyway...
And if the "multiple detection" problem does not come from the `num_queries` parameter, could you please tell me how to solve it ? 

Any help would be very much appreciated 🙏 
Thank you all !

**Comment by fmassa** [comment]
Hi,

The multiple detections might be due to many things:
- maybe you need longer training -- this depends on the `cardinality_error` that you have in your logs
- maybe you need a higher threshold? Currently DETR is calibrated in such a way that it requires a fairly high threshold for detections.

I think the `num_queries` being 100 is not necessarily the issue here, I think it should be fine.

**Comment by zobeirraisi** [comment]
@jeromen7 
I had the same problem for a one-class dataset close to your dataset, but as @fmassa discussed above, the problem of multiple-detection is solved by longer training.  At beginning of training precision and recall were far away from each other, but by increasing epochs of training without changing any setting in DETR I also got a better performance.

**Comment by jeromen7** [comment]
Thank you very much @fmassa @zobeirraisi !
I will train it more to see if there is any improvement and after that, I will write in this issue if it helped me or not.

**Comment by jeromen7** [comment]
You were right @fmassa @zobeirraisi, more training helped reducing multiple detections. It is still not perfect but it definitely helped.
Thank you again !
I am closing this issue.

**Comment by hzphzp** [comment]
> Hi,
> 
> The multiple detections might be due to many things:
> 
> * maybe you need longer training -- this depends on the `cardinality_error` that you have in your logs
> * maybe you need a higher threshold? Currently, DETR is calibrated in such a way that it requires a fairly high threshold for detections.
> 
> I think the `num_queries` being 100 is not necessarily the issue here, I think it should be fine.

Hi, I am not quite familiar with this task, could you explain what the threshold is? Thx.

**Comment by fmassa** [comment]
Threshold here means the minimum classification score so that the prediction is displayed

**Comment by hzphzp** [comment]
> Threshold here means the minimum classification score so that the prediction is displayed

@fmassa thank you for your kind reply, I have not seen the detection classification threshold code, could you help me locate it?

**Comment by fmassa** [comment]
@hzphzp we don't use it for mAP computation, and we have explained it in more detail in https://github.com/facebookresearch/detr/issues/201
