### ISSUE TITLE
num_classes for coco panoptic

### ISSUE THREAD

**Issue by Ww-Lee** [facebookresearch/detr#175]
**coco panoptic max class id = 200, why num_classes=250 ?**

    if args.dataset_file == "coco_panoptic":
        num_classes = 250

**Comment by fmassa** [comment]
The exact value doesn't matter much, and if you say that the max class id is 200 then we could probably change it.

We just added a sufficiently large value so that all class ids could fit, and we didn't check very closely so that the number is the exact one.

But maybe @alcinos can chime if there were also other reasons.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you  have further questions.

**Comment by Ww-Lee** [comment]
Thank you. One more question: 
I try to train on a small set of coco panoptic dataset, but class error is hard to reduce. May I ask if I need to change `num_classes` and `num_queries` ? Or whether to choose images with some common features from coco panoptic.

**Comment by Ww-Lee** [comment]
> The exact value doesn't matter much, and if you say that the max class id is 200 then we could probably change our `num_classes` to something smaller.
> 
> We just added a sufficiently large value so that all class ids could fit, and we didn't check very closely so that the number is the exact one.
> 
> But maybe @alcinos can chime if there were also other reasons.
> 
> I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.



> The exact value doesn't matter much, and if you say that the max class id is 200 then we could probably change our `num_classes` to something smaller.
> 
> We just added a sufficiently large value so that all class ids could fit, and we didn't check very closely so that the number is the exact one.
> 
> But maybe @alcinos can chime if there were also other reasons.
> 
> I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.



> The exact value doesn't matter much, and if you say that the max class id is 200 then we could probably change our `num_classes` to something smaller.
> 
> We just added a sufficiently large value so that all class ids could fit, and we didn't check very closely so that the number is the exact one.
> 
> But maybe @alcinos can chime if there were also other reasons.
> 
> I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.

Thank you. One more question: 
I try to train on a small set of coco panoptic dataset, but class error is hard to reduce. May I ask if I need to change `num_classes` and `num_queries` ? Or whether to choose images with some common features from coco panoptic.

**Comment by Ww-Lee** [comment]
> The exact value doesn't matter much, and if you say that the max class id is 200 then we could probably change our `num_classes` to something smaller.
> 
> We just added a sufficiently large value so that all class ids could fit, and we didn't check very closely so that the number is the exact one.
> 
> But maybe @alcinos can chime if there were also other reasons.
> 
> I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.

Thank you. One more question: 
I try to train on a small set of coco panoptic dataset, but class error is hard to reduce. May I ask if I need to change `num_classes` and `num_queries` ? Or whether to choose images with some common features from coco panoptic.

**Comment by fmassa** [comment]
If your class labels are the same, then no need to change anything and you can keep everything as is, including finetuning on it
