### ISSUE TITLE
Bug in pad operation in transforms.py

### ISSUE THREAD

**Issue by Epiphqny** [facebookresearch/detr#182]
Is this a bug?
https://github.com/facebookresearch/detr/blob/6a608d3c3a9e10403379f7e7f65f48e26d03f645/datasets/transforms.py#L142
should it be 
`target["size"] = torch.tensor(padded_image.size[::-1]) ` ?

**Comment by fmassa** [comment]
Yes, looks like it's a bug, but we should be careful with the fix because it should not include the `channel` dimension, only height and width.

Can you send a PR fixing it?

**Comment by fmassa** [comment]
Fixed in https://github.com/facebookresearch/detr/pull/187
