### ISSUE TITLE
attention visualization 

### ISSUE THREAD

**Issue by Mrkkew** [facebookresearch/detr#183]
Hello, I want to konw how to visualize the encoder attention and decoder attention for every predict object. I cannot find this part in your code. How do you achieve this?

**Comment by fmassa** [comment]
Hi,

We have the attention visualization in https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb

I believe I have answered your question and as such I'm closing this issue, but let us know if there is something else that you are looking for that is not in the notebooks.

**Comment by GivanTsai** [comment]
> 

Why this code can not run successfully on vscode?
