### ISSUE TITLE
Where should the datasets be placed? Please help me

### ISSUE THREAD

**Issue by Pianllo** [facebookresearch/detr#189]
Hello,
we are college students who are very interested in your paper. We have imported all the necessary conditions, but we want to consult which directory the dataset should be placed in.
We only want to reproduce the process of your paper, so we did not do anything to the original codes.
We created a new folder named _path_, and then created a _to_ folder in it, then created a _coco_ folder in _to_, and finally put the three datasets(annotations, train2017, val2017) into.
Yours,
Pianllo

**Comment by lessw2020** [comment]
Hi @Pianllo 
You can place the dataset where you want, you just need to set the args.coco_path to point to it. The code is in coco.py for reference if you need to adjust the subdirs:
def build(image_set, args):
    root = Path(args.coco_path)
    assert root.exists(), f'provided COCO path {root} does not exist'
    mode = 'instances'
    PATHS = {
        "train": (root / "train2017", root / "annotations" / f'{mode}_train2017.json'),
        "val": (root / "val2017", root / "annotations" / f'{mode}_val2017.json'),
    }
Im assuming you just want to run coco dataset.
For your own custom data then there are other changes.
Hope this helps!

**Comment by fmassa** [comment]
@lessw2020 has answered your question, and as such I'm closing this issue, but let us know if you have further questions
