### ISSUE TITLE
Could you help me to understand why the test performance would drop if the test batch size increase? 

### ISSUE THREAD

**Issue by Weixin-Liang** [facebookresearch/detr#191]
Hi, Thanks for the wonderful repo! 

The evaluation section in the readme says "Note that numbers vary depending on batch size (number of images) per GPU. Non-DC5 models were trained with batch size 2, and DC5 with 1, so DC5 models show a significant drop in AP if evaluated with more than 1 image per GPU." If I understand it correctly, does it say that the test performance would drop if the test batch size increase? If so, could you help me to understand what is the reason behind that? It seems that normally the test time batch size would not affect test performance. Thanks for your reply!

**Comment by alcinos** [comment]
Hi @Weixin-Liang 
Thank you for your interest in DETR.

Models that are trained with 1 image/gpu are not trained to see batches that contain padding, which occurs only when 2 or more images with different sizes are batched together. As a result, any batch that contains padding (ie most of the times when there is > 2 images) will be out of distribution, resulting in lower performance.
Note that many other scenarios will work fine, eg training with batch_size=2 and testing with batch_size=4 should be perfectly fine. 

I believe I have answered your question and as such I'm closing this. If you have further concerns, feel free to reach out.
