### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by xuaiyishen2012** [facebookresearch/detr#196]
Hi,when I ran this network,I met an issue like this:
ValueError: num_samples should be a positive integer value, but got num_samples=0

my num_classes=1,and I made sure that the category_id is 0.I made the right path to images and annotations.I don't know what this error exactly means,could you help me out?

**Comment by fmassa** [comment]
Hi,

We need more information on the error message and what you are trying to do to help.

My first guess is that your dataset might be empty, so it has no images that were found and thus the Sampler fails.

**Comment by xuaiyishen2012** [comment]
Hi,thank you for answering my question.
I'm doing object detection.I want to train a dataset which only includes one class:bridge.
I put the data file folder under the detr-master file folder.and images and annotations are in the corresponding path as the code said.I don't know why there is no images found.


the changes of code I have made are as follows:
models-&gt;detr.py-&gt;def build(args):num_classes = 1


my total error is attached.
please help me out.


Looking forward to your reply.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午3:53
收件人:&nbsp;"facebookresearch/detr"<detr@noreply.github.com&gt;;
抄送:&nbsp;"1979771495"<1979771495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detr] ValueError: num_samples should be a positive integer value, but got num_samples=0 (#196)





 
Hi,
 
We need more information on the error message and what you are trying to do to help.
 
My first guess is that your dataset might be empty, so it has no images that were found and thus the Sampler fails.

**Comment by fmassa** [comment]
Hi,

If you put a print like
```python
print(len(dataset_train))
print(len(dataset_val))
```
just after https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/main.py#L142-L144
you'll see that it will give 0.

This can be for a number of reasons, including that your data is not formatted in the way the code expects it, or that you need to change https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/main.py#L83 to point to the correct place.

Also note that the current implementation assumes that the dataset follows the COCO format.

**Comment by xuaiyishen2012** [comment]
Hi,is that may be the format of .json file is wrong?is there any requirement of the format of images?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 下午4:48
收件人:&nbsp;"facebookresearch/detr"<detr@noreply.github.com&gt;;
抄送:&nbsp;"1979771495"<1979771495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detr] ValueError: num_samples should be a positive integer value, but got num_samples=0 (#196)





 
Hi,
 
If you put a print like
 print(len(dataset_train)) print(len(dataset_val))
 
just after https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/main.py#L142-L144
 you'll see that it will give 0.
 
This can be for a number of reasons, including that your data is not formatted in the way the code expects it, or that you need to change https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/main.py#L83 to point to the correct place.
 
Also note that the current implementation assumes that the dataset follows the COCO format.

**Comment by fmassa** [comment]
The `.json` should be compatible with COCO dataset format, and the images currently need to be in a folder named `train2017` and `val2017`, and the annotations should also have compatible names `instances_train2017.json` and `instances_val2017.json`, and this can all be changed in https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/datasets/coco.py#L152-L153

**Comment by xuaiyishen2012** [comment]
thank you very much,there is one more question:why the num_class don't have to add one(background)?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 晚上7:09
收件人:&nbsp;"facebookresearch/detr"<detr@noreply.github.com&gt;;
抄送:&nbsp;"1979771495"<1979771495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detr] ValueError: num_samples should be a positive integer value, but got num_samples=0 (#196)





 
The .json should be compatible with COCO dataset format, and the images currently need to be in a folder named train2017 and val2017, and the annotations should also have compatible names instances_train2017.json and instances_val2017.json, and this can all be changed in https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/datasets/coco.py#L152-L153

**Comment by fmassa** [comment]
> why the num_class don't have to add one(background)?

This is already handled in the codebase in https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/models/detr.py#L37

I believe I've answered your questions, and as such I'm closing this issue but let us know if you have further questions

**Comment by xuaiyishen2012** [comment]
Thank you for your kind assistance！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 晚上8:57
收件人:&nbsp;"facebookresearch/detr"<detr@noreply.github.com&gt;;
抄送:&nbsp;"1979771495"<1979771495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detr] ValueError: num_samples should be a positive integer value, but got num_samples=0 (#196)





  
why the num_class don't have to add one(background)?
  
This is already handled in the codebase in https://github.com/facebookresearch/detr/blob/e8eab5937da45575dc3bc3cfe31062b5db35b461/models/detr.py#L37
 
I believe I've answered your questions, and as such I'm closing this issue but let us know if you have further questions

**Comment by foysalahmed10** [comment]
Hello Sir,
I was trying to train my own dataset in VoteNet. In my dataset have 3 classes. This dataset was prepared for instance segmentation. I  build a new data class(PlantNet),i am modify the  scannet (scannet_detection_dataset.py and model_util_scannet.py) file. Follow through [.](https://github.com/facebookresearch/votenet/blob/master/doc/tips.md). When I start training it showing an error.  In this dataset, I don't use any images. 


Error:
kept 0 scans out of 3640
kept 0 scans out of 1820
0 0
Traceback (most recent call last):
  File "train.py", line 155, in <module>
    shuffle=True, num_workers=4, worker_init_fn=my_worker_init_fn)
  File "/home/foysal/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/home/foysal/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
