### ISSUE TITLE
something wrong in loss mapping

### ISSUE THREAD

**Issue by xuaiyishen2012** [facebookresearch/detr#197]
Hi,
when I ran the plot_utils.py code to draw my loss chart,there isn't any error,but also nothing happened.Is there something wrong with my operation?

**Comment by fmassa** [comment]
Hi,

I think what might happen is that you only have one epoch in your log file, so that it only shows a single point (which can appear as an empty plot).
Can you double-check?

**Comment by xuaiyishen2012** [comment]
Hi,
If I were to resume training after a break in training, what parameters would I need to change?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 晚上6:43
收件人:&nbsp;"facebookresearch/detr"<detr@noreply.github.com&gt;;
抄送:&nbsp;"1979771495"<1979771495@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detr] something wrong in loss mapping (#197)





 
Hi,
 
I think what might happen is that you only have one epoch in your log file, so that it only shows a single point (which can appear as an empty plot).
 Can you double-check?

**Comment by fmassa** [comment]
Just pass `--resume <path/to/your/checkpoint.pth>` and the same hyperparameters as originally used to run the model and it should be fine.

I believe I've answered your question, so I'm closing this issue but let us know if you have further questions
