### ISSUE TITLE
Run panoptic segmentation

### ISSUE THREAD

**Issue by SharifElfouly** [facebookresearch/detr#20]
Great paper and repo btw, congrats!

I wanted to do a simple single image inference with the panoptic segmentation model. I archived that in a very 'hacky' way by editing the `main.sh` file (Can be seen [here](https://github.com/SharifElfouly/detr-panoptic)).

Are you planing to release a demo notebook like the one for object detection or uploading the .pth files to torch.Hub?

**Comment by fmassa** [comment]
Hi,

Thanks for the message!

We are planning on releasing a colab notebook illustrating how to perform predictions with `detr_panoptic`, and we will also include torchhub models for it. It should be available sometime next week.

**Comment by SharifElfouly** [comment]
Awesome, thanks for the info!

**Comment by alcinos** [comment]
Hi all, the panoptic notebook is now available here https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/DETR_panoptic.ipynb
cc @shidilrzf 
Let me know what you think.

**Comment by SharifElfouly** [comment]
Thank you this is super helpful!

I had to upgrade pyyaml for whatever reason.
Just run:
`pip3 install pyyaml -U`
if you run into the same error.

**Comment by shidilrzf** [comment]
Thanks a lot! That really helped.
 I had some problems with metadata to be able to use detecton2 Visualizer. The category-id reported in the "segment_info" was different than the one used in detectron2.

**Comment by rkinas** [comment]
I made simple demo using DETR and panoptic segmentation here:

https://youtu.be/CJj6V1eafVs

Each class has predefined color (to prevend color blinking on video).

**Comment by shidilrzf** [comment]
> > Thanks a lot! That really helped.
> > I had some problems with metadata to be able to use detecton2 Visualizer. The category-id reported in the "segment_info" was different than the one used in detectron2.
> 
> Yes indeed, Detectron2 does a remapping to ensure contiguous IDs, which we don't. Did the Notebook clarify that part for you?

Yes, thanks a lot ;)

**Comment by alcinos** [comment]
I believe the issue at hand was addressed, as such I'm closing this. Feel free to ask if you have further questions.

**Comment by NIkimih** [comment]
Is it possible to train panoptic segmentation on my dataset, which is not in COCO format? @alcinos

**Comment by alcinos** [comment]
@NIkimih We currently only support COCO format. You'll need to convert your dataset, see https://cocodataset.org/#format-data for information on what is expected. You essentially need three things: the images, some jsons (for train and val) describing the segments (class, associated bounding box, id), and a specially formatted png encoding per-pixel segment ids (the color correspond to the id, as described in the link)

**Comment by NIkimih** [comment]
> @NIkimih We currently only support COCO format. You'll need to convert your dataset, see https://cocodataset.org/#format-data for information on what is expected. You essentially need three things: the images, some jsons (for train and val) describing the segments (class, associated bounding box, id), and a specially formatted png encoding per-pixel segment ids (the color correspond to the id, as described in the link)

Thanks for the quick response

**Comment by sodi16** [comment]
Hii, after running panoptic segmentation on my image: `panoptic_seg_map, segments_info = predictor(im)["panoptic_seg"]`, I want to know the to wich label class, each pixel of my seg_map belong.
I though they belong to COCO classes labels, but they are not. If someone know the answer, thanks in advance.

**Comment by sodi16** [comment]
Hii, can someone explain me how areas is calculate in panoptic segmentation ouput? Thanks in advance
```
segments_info = [{'area': 2712.0,
  'category_id': 0,
  'id': 1,
  'instance_id': 0,
  'isthing': True,
  'score': 0.9890128374099731},
```
