### ISSUE TITLE
Question about plot_precision_recall function

### ISSUE THREAD

**Issue by 1chimaruGin** [facebookresearch/detr#203]
## ❓ How to use plot_precision_recall function?

Hello, thanks for sharing this amazing work! 

I was trying to plot my training logs

In util/plot_utils.py
`def plot_precision_recall(files, naming_scheme='iter'):`

What does the files mean? 

'log.txt' or path?

**Comment by ilem777** [comment]
@1chimaruGin I would also like to know, how did you achieve this?
