### ISSUE TITLE
Adapt pre-trained DETR to custom dataset ?

### ISSUE THREAD

**Issue by whatdhack** [facebookresearch/detr#205]
What are the steps involevd in adapting (fine tunning)  pre-trained DETR for  custom dataset ?

**Comment by alcinos** [comment]
I invite you to look at the discussion in #9 and ask questions there if anything is unclear.

**Comment by whatdhack** [comment]
Thanks.  There are way too many messages to go through.  Not knowing which ones are relevant, makes it time consuming.  However, after  reading a few of the messages,  I get the impression that fine tunning on custom data is possible. It would help a lot to have a readme somewhere with the  essentials of discussion https://github.com/facebookresearch/detr/issues/9 .

**Comment by 1chimaruGin** [comment]
@whatdhack 

https://gist.github.com/m-klasen/651297e28199b4bb7907fc413c49f58f

**Comment by whatdhack** [comment]
Thanks that helped, Works for COCO data sets.  However  does not work for non-COCO data sets.  To be specific  fails at engine.py: 

```
        if coco_evaluator is not None:
            coco_evaluator.update(res)
```

What is the best way to get around that ?

**Comment by 1chimaruGin** [comment]
@whatdhack 

you mean your custom data is not COCO format?
If your dataset wasn't COCO format, you won't be able to use coco_evaluator.

[Check this notebook](https://github.com/woctezuma/finetune-detr) for finetuning custom dataset by [woctezuma](https://github.com/woctezuma)

**Comment by whatdhack** [comment]
Yes, I gathered that much.   Seeing very low pecision  ~ 0.001.  How do I  track/debug this ?  Do not see any errror/warning anywhere.

**Comment by whatdhack** [comment]
Would be great to see some stats on the images and annotations in the log. That will help in debugging the  data ingest part.
