### ISSUE TITLE
Why Transformer  not BERT in DETR ?

### ISSUE THREAD

**Issue by whatdhack** [facebookresearch/detr#206]
Wondering why the choice of Transformer in DETR , rather than  BERT ?  BERT only uses encoder part of Transformer.

**Comment by alcinos** [comment]
I invite you to read our paper (https://arxiv.org/abs/2005.12872) or watch our explanatory video (https://www.youtube.com/watch?v=utxbUlo9CyY). Note that a decoder is required to make DETR work at all. 
If you have specific questions after that, feel free to ask.

**Comment by whatdhack** [comment]
Thanks, looks like  "The encoder seems to separate instances already, which
likely simplifies object extraction and localization for the decoder. " is the current hypotheis. 

"... (Table 2). Without
encoder layers, overall AP drops by 3.9 points, with a more significant drop of
6.0 AP on large objects. We hypothesize that, by using global scene reasoning,
the encoder is important for disentangling objects. In Figure 3, we visualize the
attention maps of the last encoder layer of a trained model, focusing on a few
points in the image. The encoder seems to separate instances already, which
likely simplifies object extraction and localization for the decoder. "
