### ISSUE TITLE
D2 example train_net not using DetrDatasetMapper for test

### ISSUE THREAD

**Issue by ccarter-cs** [facebookresearch/detr#209]
It appears that the DetrDatasetMapper is not used for valid/test, only train. I haven't run any tests, so sorry if this is incorrect.

**Comment by edwardpwtsoi** [comment]
Hi @ccarter-cs,
The DetrDatasetMapper is actually very similar to a default [DatasetMapper](https://detectron2.readthedocs.io/_modules/detectron2/data/dataset_mapper.html#DatasetMapper) in detectron2.
I have been using the d2 wrapper for a while, it works fine to me.

**Comment by ccarter-cs** [comment]
Good to hear. I'll close this.
