### ISSUE TITLE
Additional losses and CUDA out of memory issue

### ISSUE THREAD

**Issue by Madhusakth** [facebookresearch/detr#214]
I am trying to train on images with an additional channel. 4 instead of 3 channels. So, I loaded the model and modified the backbone conv1 layer, and while the rest were the pre-trained weights. 

+    model.backbone[0].body.conv1 = nn.Conv2d(4, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
-        T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
+        T.Normalize([0.485, 0.456, 0.406,0], [0.229, 0.224, 0.225,1])

I got CUDA out of memory after 3 epochs in the middle of training. However, if I try to run the code and resume from the saved model, I'm getting additional errors. 

something like this: Epoch: [3]  [   10/19023]  eta: 1:36:56  lr: 0.000100  class_error: 100.00  loss: 20.6389 (20.8001)  loss_ce: 0.8912 (0.8701)  loss_bbox: 0.4998 (0.4750)  loss_giou: 1.3053 (1.2377)  loss_ce_0: 1.1391 (1.1219)  loss_bbox_0: 0.8745 (1.0760)  loss_giou_0: 1.6266 (1.6532)  loss_ce_1: 0.9242 (0.9986)  loss_bbox_1: 0.7492 (0.8822)  loss_giou_1: 1.7428 (1.7269)  loss_ce_2: 0.9697 (0.9294)  loss_bbox_2: 1.2141 (1.2966)  loss_giou_2: 2.0571 (2.0193)  loss_ce_3: 0.9890 (0.9961)  loss_bbox_3: 0.8386 (0.8930)  loss_giou_3: 1.6894 (1.7001)  loss_ce_4: 1.0275 (0.9936)  loss_bbox_4: 0.5459 (0.6039)  loss_giou_4: 1.3956 (1.3266)  loss_ce_unscaled: 0.8912 (0.8701)  class_error_unscaled: 100.0000 (97.3485)  loss_bbox_unscaled: 0.1000 (0.0950)  loss_giou_unscaled: 0.6526 (0.6188)  cardinality_error_unscaled: 3.5000 (5.1818)  loss_ce_0_unscaled: 1.1391 (1.1219)  loss_bbox_0_unscaled: 0.1749 (0.2152)  loss_giou_0_unscaled: 0.8133 (0.8266)  cardinality_error_0_unscaled: 8.0000 (9.0455)  loss_ce_1_unscaled: 0.9242 (0.9986)  loss_bbox_1_unscaled: 0.1498 (0.1764)  loss_giou_1_unscaled: 0.8714 (0.8634)  cardinality_error_1_unscaled: 3.5000 (3.5909)  loss_ce_2_unscaled: 0.9697 (0.9294)  loss_bbox_2_unscaled: 0.2428 (0.2593)  loss_giou_2_unscaled: 1.0285 (1.0097)  cardinality_error_2_unscaled: 4.0000 (3.9545)  loss_ce_3_unscaled: 0.9890 (0.9961)  loss_bbox_3_unscaled: 0.1677 (0.1786)  loss_giou_3_unscaled: 0.8447 (0.8500)  cardinality_error_3_unscaled: 4.0000 (3.9545)  loss_ce_4_unscaled: 1.0275 (0.9936)  loss_bbox_4_unscaled: 0.1092 (0.1208)  loss_giou_4_unscaled: 0.6978 (0.6633)  cardinality_error_4_unscaled: 4.0000 (3.9545)  time: 0.3059  data: 0.0254  max mem: 4013

and then it quickly runs out of CUDA memory. I did git diff to the original code and the modifications I've made to DETR code is replacing the CNN layer, and adding a parameter to normalization to account for the additional channel. 

Thanks in advance!

**Comment by netw0rkf10w** [comment]
Try a smaller batch size maybe?

**Comment by alcinos** [comment]
May I ask what is this 4th channel for? It's quite unlikely that the surgery you did will give any decent results, you should probably preretrain the backbone on some classification task (or do unsupervised pre-training, like this paper: https://arxiv.org/abs/2006.09882)
Apart from that, I'll just guess that you don't have enough gpu memory. It's not uncommon for the OOM to occur anytime in training, it just takes an unlucky batch.

**Comment by lvaleriu** [comment]
This 4-th channel can contain additional useful information that could help object detection. At least in my case.
