### ISSUE TITLE
[Question] The performance of DETR on small objects

### ISSUE THREAD

**Issue by cfzd** [facebookresearch/detr#215]
Hi, as the paper said, DETR has a relatively poor performance on small objects. I'm wondering what might be the reason for this phenomenon.

In my opinion, there are two major steps for DETR to recognize an object. 
- The first step is to attend objects via self-attention. 
- The second one is to query the objects. 

So which step is not working for small objects? Is it because the small object is too small to attend? Or the encoder could indeed attend the small objects, but the decoder can't query the small object via learned queries?

**Comment by fmassa** [comment]
Hi,

The current hypothesis is that the feature maps that we feed to the encoder (and then decoder) have a coarse resolution (divided by 32), which makes it harder for the model to precisely localize small objects (smaller than 32 pixels)
