### ISSUE TITLE
[Question] Is the 'output.unsqueeze(0)' necessary in your transformer decoder?

### ISSUE THREAD

**Issue by hojunroks** [facebookresearch/detr#219]
Hello. I'm trying to implement a simpler version of DETR following your code.
I've noticed that in your transformer decoder you have an additional unsqueeze at the return of the forward function.
I can't find why this extra dimension is needed, as it's not used in neither the entire transformer module nor the DETR model.
Is there something I'm missing?

**Comment by alcinos** [comment]
Hi @hojunroks 
The our decoder implementation is modified to return several intermediate layers. This is needed for the auxiliary losses.
During training, here is the line that is normally executed:
https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/transformer.py#L121-L122

During inference, intermediate layers are no longer required, so we can simply return the last layer, and the unsqueeze you're referring to makes sure the dimensions are similar to the case above. That is done in this line:
https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/transformer.py#L124

When we compute the heads, we compute them in parallel for all intermediate layers:
https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/detr.py#L67-L69
However, notice the `outputs_class[-1]` which retrieves the output corresponding to the last layer only (or, in inference, to the only layer available). This is where the extra dimension is removed.

Hope this helps.
I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.

**Comment by hojunroks** [comment]
Thanks a lot! I paid little attention to the part with intermediate layers. Now I understand that the unsqueeze is part of well-written code.
