### ISSUE TITLE
Predictions using ground truth bounding box coordinates

### ISSUE THREAD

**Issue by cjrd** [facebookresearch/detr#228]
I'm interested in performing an ablation using DETR in which the ground truth bounding box coordinates are supplied during evaluation. Is there a way to do this with the codebase?

Thanks!

**Comment by fmassa** [comment]
Hi,

You would need to write a bit of code for it, but it shouldn't be too hard. The easiest would be to use the Matcher to find the best assignment between the predictions and the ground-truth, and then replace the predicted boxes with the GT boxes.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.
