### ISSUE TITLE
Multi-oriented or quadrilateral object detection?

### ISSUE THREAD

**Issue by zobeirraisi** [facebookresearch/detr#231]
Right now DETR because of rectangle bboxes of COCO-dataset produces rectangle-bboxes outputs, if we had quadrilateral bboxes (8 points), which parts of the architecture must be modified to output a quadrilateral shape bboxes?

**Comment by fmassa** [comment]
Hi,

You would need to change the number of prediction point https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/detr.py#L38, the loss for the bounding boxes https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/detr.py#L143-L162, the postprocessing https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/detr.py#L277-L282 and assignment cost for the boxes https://github.com/facebookresearch/detr/blob/5e66b4cd15b2b182da347103dd16578d28b49d69/models/matcher.py#L71-L74

Also note that the GIoU loss was very important for DETR, so you might need to find an equivalent type of loss if using different polygons.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions

**Comment by yellowjs0304** [comment]
@zobeirraisi Hi, did you succeed it?

**Comment by zobeirraisi** [comment]
> @zobeirraisi Hi, did you succeed it?

Yes

**Comment by yellowjs0304** [comment]
@zobeirraisi Thanks for fast reply. 
Could you please give me some tips? 
or Are there any opened code that I can refer to?

**Comment by zobeirraisi** [comment]
> @zobeirraisi Thanks for fast reply. 
> 
> Could you please give me some tips? 
> 
> or Are there any opened code that I can refer to?

I am in trip now and don't access to my PC but I will share the code when I get access to it

**Comment by yellowjs0304** [comment]
@zobeirraisi Hi, I hope you had a good trip :) Is there any info about it? I'm still wait it.
+) Perhaps, Is this related with this [repo](https://github.com/zobeirraisi/DRDETR/tree/main/models)?
