### ISSUE TITLE
Why evaluating with a larger batchsize for DC5 will hurt the performance?

### ISSUE THREAD

**Issue by tangjiuqi097** [facebookresearch/detr#239]
![image](https://user-images.githubusercontent.com/22868536/93581555-e4c8c500-f9d3-11ea-9542-2bfb1717537d.png)

It is hard to understand why the batchsize affect the performance at evaluate phase.

**Comment by fmassa** [comment]
Hi,

We answered this question in https://github.com/facebookresearch/detr/issues/217#issuecomment-684087741

Quoting @alcinos 
> However, I want to stress that a model trained with bs=1 per card won't do well if tested with bs > 1. The reason is that it will never have encountered padding at train time, and thus will be confused when encountering it at test time. The drop is estimated at ~10 mAP if you train with 1 img/card and test with 2 img/card. This applies to our DC5 models in particular.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions
