### ISSUE TITLE
Input size for evaluting

### ISSUE THREAD

**Issue by nahidq** [facebookresearch/detr#245]
Thanks for sharing the code.  I want to evaluate my data set, should I resize input image or does it accept any input size?

Thanks

**Comment by fmassa** [comment]
Hi,

You should resize the input to have a minimum size of 800 (and ideally a max size of 1333), the model doesn't do the resizing inside it. Check our colab notebook for further details on how to perform the input preprocessing https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions/

**Comment by nahidq** [comment]
Hi,

Thanks for answering my question.

Best regards,
Nahid
