### ISSUE TITLE
How to replace the backbone with resnext

### ISSUE THREAD

**Issue by Epiphqny** [facebookresearch/detr#250]
Thanks for your work, I want to replace the backbone with resnext network, with only changing the code of main.py to resnext50_32x4d the code runs. Nut I wonder if it is correct, do I need to modify the code in backbone.py ?

**Comment by fmassa** [comment]
Hi,

This should be enough to pass `resnext50_32x4d` in `--backbone` to use ResNeXt, but you'll need to train the model from scratch as we don't provide pretrained DETR models with ResNeXt backbone.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions
