### ISSUE TITLE
Is it possible to perform additive modifications to DETR while the modified model's training is still able to resume from a standard DETR checkpoint?

### ISSUE THREAD

**Issue by HawkRong** [facebookresearch/detr#254]
I plan to perform some modifications to DETR, like adding an additional network branch in parallel with the transformer branch. I plan to keep all original DETR components complete.
In this case, is it possible to load a standard DETR checkpoint to initialize the DETR compoents in my new model at the start of the training? (So that the new model's training has a better chance of converging faster?)
Thanks!

**Comment by OsamaMazhar** [comment]
You can only load the dict parameters that are common with your modified model with those in original DETR checkpoints. You will have to filter the conflicting ones out. This can be done in the main file under args.resume if statement.

**Comment by HawkRong** [comment]
@OsamaMazhar Thanks, I'll take a look into that main file. I'm also wondering if this checkpoint loading mechanism applies to the Detectron2 version of DETR?

**Comment by alcinos** [comment]
In Detectron2, you can provide WEIGHTS (see the configuration file), then the loader will load only the weights that are defined in your model and present in the weight file you provide. So if you define a new branch in the model (WITHOUT renaming anything else), then pass a pre-trained DETR as weights, it'll load the DETR part correctly and leave your new branch uninitialized, which is probably what you want.

I believe I have answered your question and as such I'm closing this. Feel free to reach out if you have further questions.

**Comment by HawkRong** [comment]
@alcinos Thank you, it's clear now.
