### ISSUE TITLE
how to train a model with mutil datasets?

### ISSUE THREAD

**Issue by Real-YeJ** [facebookresearch/detr#260]
Thanks for great work!  can anyone tell me how to train a model with mutil datasets?

**Comment by alcinos** [comment]
@Real-YeJ 
Please have a look at the pytorch documentation: https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset

I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
