### ISSUE TITLE
How to extract "encoder transformer" features from pre-trained model

### ISSUE THREAD

**Issue by kyteinsky** [facebookresearch/detr#265]
## ❓ How to extract "encoder transformer" features from pre-trained model

I load the model using torch hub
```python
model = torch.hub.load('facebookresearch/detr', 'detr_resnet101', pretrained=True)
output = model(image)
```
Now I need to extract the encoder features from the model for the given input. 
I couldn't find I way that worked for this use case. 

Could you just hint me some lines of code or suggest modifications in the py files (detr.py or transformer.py)?

Thank you

**Comment by alcinos** [comment]
Hi @kyteinsky 
One way would be to use hooks, you can have a look on how we implement visualization in our colab notebooks to see how to do that.

If you want to return it as part of the forward, you need to modify a bit the forward. The transformer already returns a tuple (decoder features, encoder features):
https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/models/transformer.py#L59
You simply need to return the latter in the forward of DETR:
https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/models/detr.py#L65
(Notice how the final [0] discards the encoder features, you can remove that and return the encoder features there)


I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.

**Comment by kyteinsky** [comment]
Thank you so much for your reply.

Saved my day. I was wondering why CUDA filled up after few batches and the reason I didn't remove the hook, saw your visualization colab noteboook and it worked like charm!!
Thanks once again!
