### ISSUE TITLE
what is the difference between  forward_post, forward_pre, and forward in the transformer

### ISSUE THREAD

**Issue by seyeeet** [facebookresearch/detr#266]
can you explain what is the differences between the   forward_post, forward_pre, and forward in the transformer.py

**Comment by fmassa** [comment]
`forward_post` and `forward_pre` are the implementations for pre-norm and post-norm in the transformers, which get dispatched via `forward`.

I believe I've answered your question, and as such I'm closing this issue but let us know if you have further questions
