### ISSUE TITLE
Why backbone pretrained weights loaded only to main process?

### ISSUE THREAD

**Issue by hitesh11** [facebookresearch/detr#268]
Hi DETR team,

First thanks for all the great work and making it open source. 

I am trying to understand the logic in the line:
https://github.com/facebookresearch/detr/blob/master/models/backbone.py#L91

```
backbone = getattr(torchvision.models, name)(
            replace_stride_with_dilation=[False, False, dilation],
            pretrained=is_main_process(), norm_layer=FrozenBatchNorm2d)
```

Why is pretrained flag set to is_main_process()? If the code is run on multiple gpu nodes with possibly multiple processes, would it work as expected? Are the weights copied from main process to all other processes in the beginning? Sorry, I am not completely familiar with distributed training and would appreciate pointers to understand this. 

Thanks so much!

**Comment by fmassa** [comment]
Hi,

It's just a micro-optimization, and multiple processes work as expected.

This is answered in more details in https://github.com/facebookresearch/detr/issues/235

Let us know if you have further questions

**Comment by alcinos** [comment]
Hi @hitesh11 
The line you are referring to is inside the model creation, which happens before wrapping the model in to the DistributedDataParallel. This wrapping occurs here:
https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/main.py#L126
and according to the documentation ensures the following: "The module is replicated on each machine and each device, and each such replica handles a portion of the input"

If you have pretrained=True, it would trigger downloading the model on all the nodes, which, at best is wasteful and at worst can lead to race conditions (if they try to write to the same file-system location)

**Comment by hitesh11** [comment]
Thanks a lot @fmassa  and @alcinos for your prompt responses and thorough explanations.
