### ISSUE TITLE
Landmark regression

### ISSUE THREAD

**Issue by bhack** [facebookresearch/detr#27]
Have you experimented this with landmarks/joints regression other then bounding boxes?
Some of the methods mentioned in the paper like "Object as points" was applied also on these joint tasks.

**Comment by fmassa** [comment]
Hi @bhack ,

We use GitHub issues for [tracking bugs or unexpected behaviors in DETR codebase](https://github.com/facebookresearch/detr/issues/new/choose).
For research-related questions, please reach out by e-mail.

Thank you for your understanding!

**Comment by bhack** [comment]
@fmassa I suppose it could be of general interest. But also as you suggest there was not contact point in the paper and in the repo.
