### ISSUE TITLE
Set predicted class to no_object before loss calculation (Ignoring predictions for loss)

### ISSUE THREAD

**Issue by krxxxxxxxanc** [facebookresearch/detr#281]
Hi,

I want to train DETR on a custom dataset. The problem is that my dataset includes the class "ignore_region", which has a bounding box over a region in the image, which is hard to detect (e.g. Multiple small cars covering eachother up). In training I want to filter detections in these regions, so they are not included in the loss calculation. In other object detection models I just removed these detections, but for DETR I always need N detections. So my plan was to set the predicted classlabel to "no_object" instead. How can I do this?

I thought of changing the classlabel after Line 222. But I don't know which value I have to change in the `outputs` tensor.

https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/models/detr.py#L215-L223

Edit:

I tried changing a value in the `outputs` tensor in line 223. But I get the following error in Line 121. Why is that? Is it impossible to change a value in `outputs`?

https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/models/detr.py#L121

Exception has occurred: RuntimeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Output 0 of UnbindBackward is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by krxxxxxxxanc** [comment]
Solved it!

**Comment by carlamao** [comment]
Hi, may I know how you solved this issue?
