### ISSUE TITLE
Setting criterion to eval

### ISSUE THREAD

**Issue by lhuasheng** [facebookresearch/detr#284]
Hi

Thank you very much for the awesome work! Just curious, why was it necessary to set criterion to eval in train_one_epoch function?

Thank you!

**Comment by fmassa** [comment]
Hi,

In the current implementation, [the `SetCriterion`](https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/models/detr.py#L83) does not have different behavior during training / evaluation, so setting `criterion.eval()` is not necessary.

But if the user tries a different type of criterion which might have a different behavior during testing (for example by returning extra information), then this would be taken care of by the `engine.py`, which is supposed to be a bit more generic than the models implemented here.

I believe I've answered your question and as such I'm closing this issue, but let us know if you have any other questions.

**Comment by lhuasheng** [comment]
Thank you so much!

**Comment by mariiak2021** [comment]
Hi @fmassa can you please tell me what is changing in the behavior of the model using .eval for the model itself? I'm having a trouble that all outputs of the model in .eval are exactly same. Can you please advice?
