### ISSUE TITLE
[Unexpected behaviors] Why can not set higher learning rate?

### ISSUE THREAD

**Issue by ngthanhtin** [facebookresearch/detr#285]
Hi, when I set higher learning rate such as 0.002, it raised an error:
 generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

But when I set smaller lr such as 0.0002, it worked.

I would like to ask how's learning rate matter it the code ? Thank you.

**Comment by fmassa** [comment]
Hi,

With higher learning rate training diverges. What you are seeing is an assert because there are `NaN`s in the model.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions
