### ISSUE TITLE
why seed = args.seed + utils.get_rank()?

### ISSUE THREAD

**Issue by amirhfarzaneh** [facebookresearch/detr#297]
Hi

My question is why the seed is added to the rank for manual seeding? Is this necessary for DDP?

**Comment by fmassa** [comment]
Hi,

This is so that each GPU has a different (but deterministic) seed, so that the data transformations that are applied are not the same between all GPUS.

I believe I've answered your question and as such I'm closing this issue but let us know if you have further questions.

**Comment by amirhfarzaneh** [comment]
Thanks @fmassa. This indeed answers my question. Clever!
