### ISSUE TITLE
[QUESTION] About the denominator in 'loss_bbox'

### ISSUE THREAD

**Issue by HawkRong** [facebookresearch/detr#299]
Looking into `class SetCriterion`, I noticed `loss_bbox` and `loss_giou` are normalized with `num_boxes` as:
```
losses['loss_bbox'] = loss_bbox.sum() / num_boxes
```
and
```
losses['loss_giou'] = loss_giou.sum() / num_boxes
```
what's the purpose of this design and why not get the mean directly?

```
def loss_boxes(self, outputs, targets, indices, num_boxes):
        """Compute the losses related to the bounding boxes, the L1 regression loss and the GIoU loss
           targets dicts must contain the key "boxes" containing a tensor of dim [nb_target_boxes, 4]
           The target boxes are expected in format (center_x, center_y, w, h), normalized by the image size.
        """
        assert 'pred_boxes' in outputs
        idx = self._get_src_permutation_idx(indices)
        src_boxes = outputs['pred_boxes'][idx]
        target_boxes = torch.cat([t['boxes'][i] for t, (_, i) in zip(targets, indices)], dim=0)

        loss_bbox = F.l1_loss(src_boxes, target_boxes, reduction='none')

        losses = {}
        losses['loss_bbox'] = loss_bbox.sum() / num_boxes

        loss_giou = 1 - torch.diag(box_ops.generalized_box_iou(
            box_ops.box_cxcywh_to_xyxy(src_boxes),
            box_ops.box_cxcywh_to_xyxy(target_boxes)))
        losses['loss_giou'] = loss_giou.sum() / num_boxes
        return losses
```
Apart from this, I'm wondering if Detr's training is extremely sensitive to `BASE_LR`, since when I use only the double of the default value, the training of a modified version of Detr (with additional personally-defined loss term) would randomly crash after tens of thousands of iterations, reporting `FloatingPointError: loss became infinite or NaN at iteration=...`, while the iterations before this all gave healthy loss values.

**Comment by alcinos** [comment]
Hi @HawkRong,
The explanation is in Appendix A.2 of our paper:

> All losses are normalized by the number of objects inside the batch. Extra care must be taken for distributed training: since each GPU receives a sub-batch, it is not sufficient to normalize by the number of objects in the local batch, since in general the sub-batches are not balanced across GPUs. Instead, it is important to normalize by the total number of objects in all sub-batches

Also, as you noticed, increasing the learning rate is likely to make the network diverge, as observed for eg in #28 

I believe I've answered your question and as such I'm closing this. Feel free to reach out if you have further concerns.
