### ISSUE TITLE
transformer decoder paraller decoding

### ISSUE THREAD

**Issue by Trami1995** [facebookresearch/detr#3]
how to realize the transformer decoder paraller decoding

**Comment by fmassa** [comment]
@Trami1995 parallel decoding is done in https://github.com/facebookresearch/detr/blob/7643649efdff31f6219b2a8399bbd231929dadea/models/detr.py#L63
As you can see, `self.query_embed.weight` is fed to the Transformer and used as the `query_pos` in https://github.com/facebookresearch/detr/blob/7643649efdff31f6219b2a8399bbd231929dadea/models/transformer.py#L58, which performs all the computations in parallel.

For information, `self.query_embed.weight` is a `100x256`tensor, so all the 100 object queries are processed in parallel inside the decoder.

**Comment by fmassa** [comment]
I believe I have answered your question, and as such I'm closing the issue, but please let us know if you have follow-up questions.
