### ISSUE TITLE
Learning loss coeffs

### ISSUE THREAD

**Issue by bhack** [facebookresearch/detr#30]
Have you experimented any techniques to learning losses coeffs (from Multi-task learning literature) hard-coded at https://github.com/facebookresearch/detr/blob/master/main.py#L73?  

Edit: 
E.g. Just to make a recent example https://arxiv.org/abs/2001.02223

**Comment by fmassa** [comment]
Hi @bhack ,

We use GitHub issues for [tracking bugs or unexpected behaviors in DETR codebase](https://github.com/facebookresearch/detr/issues/new/choose).
For research-related questions, please reach out by e-mail.

Thank you for your understanding!

**Comment by bhack** [comment]
@fmassa I suppose it could be of general interest. But also as you suggest there was not contact point in the paper and in the repo.
