### ISSUE TITLE
Why is DETR's FPS so much worse under similar GFLOPS compared to RCNN?

### ISSUE THREAD

**Issue by BCMoo** [facebookresearch/detr#304]
Hi everyone, I have a question about Table 1. in the paper.

Why is DETR's FPS so much worse under similar GFLOPS compared to RCNN?   
Take Faster RCNN-FPN+ and DETR-DC5 for example, difference of GFLOPS is 7 but FPS drop from 26 to 12.
Is this reasonable?

![image](https://user-images.githubusercontent.com/29893605/101299523-76c2ca00-386d-11eb-8259-7d9a217ca352.png)

**Comment by xbdxwyh** [comment]
Hello,@BCMoo!

As far as i am concerned,GFLOPS is a important metric for evaluating the speed of NN models theoretically,but it is not the only factor for impacting the speed of a model in real world.There still are many other factors which can have impact on the speed of a NN model in real world,such as the bandwidth between GPU/CPU and Memory.But those factors are difficult to quantize in paper.For this details, you can refer the paper of ShuffleNet V2.

**Comment by alcinos** [comment]
@xbdxwyh  is absolutely correct.
 Also note that convolution kernels have been around for a long time and have been considerably optimized, while transformer blocks are still relatively new and thus may not have reached their full potential on the hardware yet.
I believe your question has been answered, and as such  i'm closing this. Feel free to reach out if you have further concerns.
