### ISSUE TITLE
[Error] Maybe a wrong in codes?

### ISSUE THREAD

**Issue by GuHongyang** [facebookresearch/detr#305]
Hello, I found that when build_transformer(args), return_intermediate_dec=True.

https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/models/transformer.py#L285

In this case, the ‘intermediate‘ will be returned as follows.

https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/models/transformer.py#L104-L124

As we have seen, intermediate[-1] is the feature after all decoders, but in actual use, only [0] is used. Maybe we should change this to hs = self.transformer(self.input_proj(src), mask, self.query_embed.weight, pos[-1])[-1]. I am not sure if I understand it correctly.

https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/models/detr.py#L65

**Comment by GuHongyang** [comment]
0.0

**Comment by imhgchoi** [comment]
Any follow-ups about this? I was skimming through the codes and was curious about this as well.

**Comment by imhgchoi** [comment]
> Any follow-ups about this? I was skimming through the codes and was curious about this as well.

Seems that the transformer module returns a tuple of (hs, memory). That's why index 0 is used to grab hs.
Should've had a closer look. My bad.
