### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Murasame03** [facebookresearch/detr#306]
Hi.
Thanks for your excellent work.
I tried to train DETR following [README.md](https://github.com/facebookresearch/detr/blob/master/README.md) in Colab.
First, downloading and extracting COCO 2017 train and images with annotations as datasets file, I tried to train with them.
The directory structure is as follows:

detr-master/path/to/coco
|--train2017
|--val2017
|--annotations--instances_train2017, and so on. (extracted [Train/Val annotations](http://images.cocodataset.org/annotations/annotations_trainval2017.zip) here.)

But when I ran main .py, colab threw an error:

> Namespace(aux_loss=True, backbone='resnet50', batch_size=2, bbox_loss_coef=5, clip_max_norm=0.1, coco_panoptic_path=None, coco_path='/content/drive/My Drive/lab/detr-master/path/to/coco', dataset_file='coco', dec_layers=6, device='cuda', dice_loss_coef=1, dilation=False, dim_feedforward=2048, dist_url='env://', distributed=False, dropout=0.1, enc_layers=6, eos_coef=0.1, epochs=300, eval=False, frozen_weights=None, giou_loss_coef=2, hidden_dim=256, lr=0.0001, lr_backbone=1e-05, lr_drop=200, mask_loss_coef=1, masks=False, nheads=8, num_queries=100, num_workers=2, output_dir='', position_embedding='sine', pre_norm=False, remove_difficult=False, resume='', seed=42, set_cost_bbox=5, set_cost_class=1, set_cost_giou=2, start_epoch=0, weight_decay=0.0001, world_size=1)
number of params: 41302368
loading annotations into memory...
Done (t=15.14s)
creating index...
index created!
loading annotations into memory...
Done (t=0.45s)
creating index...
index created!
Start training
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 198, in main
    args.clip_max_norm)
  File "/content/drive/My Drive/lab/detr-master/engine.py", line 28, in train_one_epoch
    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
  File "/content/drive/My Drive/lab/detr-master/util/misc.py", line 225, in log_every
    iter_test = iter(iterable)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/lab/detr-master/datasets/coco.py", line 24, in __getitem__
    img, target = super(CocoDetection, self).__getitem__(idx)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/coco.py", line 131, in __getitem__
    img = Image.open(os.path.join(self.root, path)).convert('RGB')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/lab/detr-master/path/to/coco/train2017/000000536535.jpg'

I understand there is no image named "000000536535.jpg" in train2017, but I don't know why that happened.
Another image was not found even though I had deleted description about image which was not found in train2017 from instance.

I'm beginner of english, and ML.
Sorry for the poor English.
Thanks.

**Comment by zhaochao2018** [comment]
Hi, Murasame03.
I also met this problem. Have you solved it?

**Comment by alcinos** [comment]
Hi @Murasame03
Could you show the results of the following command:
`ls "/content/drive/My Drive/lab/detr-master/path/to/coco/train2017" | head`
Best of luck

**Comment by zhaochao2018** [comment]
Hi, thank you for your reply. 

I have found and solved my problem, which is caused by my json file being modified in previous experiments.
Thanks again.

Best of luck.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 上午8:36
收件人:&nbsp;"facebookresearch/detr"<detr@noreply.github.com&gt;;
抄送:&nbsp;"走 X 走 召"<772471980@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [facebookresearch/detr] FileNotFoundError: [Errno 2] No such file or directory (#306)





 
Hi @Murasame03
 Could you show the results of the following command:
 ls "/content/drive/My Drive/lab/detr-master/path/to/coco/train2017" | head
 Best of luck
