### ISSUE TITLE
Training DETR with different backbone

### ISSUE THREAD

**Issue by ayberksener** [facebookresearch/detr#307]
I want to train DETR with a different backbone, so how could I change the backbone.py. Kindly help me with the starter code in this regard. @lessw2020 @fmassa

**Comment by lessw2020** [comment]
Hi @ayberksener,
There's some code and an example for mobilenet implementation here:
https://github.com/facebookresearch/detr/issues/154

Hope that helps!

**Comment by ayberksener** [comment]
@lessw2020 @fmassa I trained my network with different backbone (mobilenet_v2) and the network is not converging. Any help in this regard. Thank you

**Comment by alcinos** [comment]
Hi, for help with training on your custom dataset, I recommend checking out #9
Since you seem to have figured out training with mobilenet,  I'm closing this. Feel free to reach out if you have further questions.
