### ISSUE TITLE
size_divisibility for fpn alike segmentation

### ISSUE THREAD

**Issue by nalbwa** [facebookresearch/detr#312]
hi,

while reading the code, I recognized that size_divisibility is not used in Detr.
Rather, when segmenting, it interpolates to the absolute size of the next feature to be added. (segmentation.py)
In contrast, Detectron2 used size_divisibility to pad the images and scales up by x2 when forwarding fpn.

I surely agree that the way Detr interpolates would work properly, but have a little question whether the final score using the padding by Detr is going to be slightly higher than Detectron2, or the opposite.
Has anyone tried padding by size_divisilbility?

**Comment by alcinos** [comment]
I think the size_divisibility doesn't make much difference in the final results, based on what I had observed in preliminary experiments. I have not conducted a systematic study though.

**Comment by nalbwa** [comment]
Thanks @alcinos for answering the question! :)
