### ISSUE TITLE
How to train with specific loss

### ISSUE THREAD

**Issue by nghiemvdv** [facebookresearch/detr#315]
I want to train my DETR model with either giou or l1 loss with classification loss like in the ablation of the paper.
I just want some confirmation about the giou_loss_coef and bbox_loss_coef parameters, if set one of them to 0 (let's say ```--giou_loss_coef=0```) ,or even both, i.e. ```--giou_loss_coef=0 --bbox_loss_coef=0```), does this effectively stop the model from using said loss in ```losses.backward()```, or do I have to manually remove the loss in ```loss_boxes``` function of ```SetCriterion``` class in ```detr.py``` to stop it from being calculated?

**Comment by alcinos** [comment]
Hi @nghiemvdv 
The losses will be computed anyways, but the coefficient will ensure that no gradient flows during the backward.

If you want to prevent the losses to be computed, you need to modify the code accordingly. Note that we recommend using the same parameters for each loss and their corresponding cost (for giou_loss_coef and set_cost_giou). If you set both bbox and giou to 0, the matching is unlikely to converge to anything though.

I believe I have answered your question and as such I am closing this. Feel free to reach out if you have further concerns.
