### ISSUE TITLE
The data augmentation is different between coco_panoptic and coco?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/detr#323]
The data augmentation is different between coco_panoptic and coco? It seems like coco_panoptic does not add any data augmentation strategy.

**Comment by alcinos** [comment]
From the dataset file, you can see that coco_panoptic uses the same transforms as coco:
https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/datasets/coco_panoptic.py#L97

The exact same augmentation strategies are used.
I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
