### ISSUE TITLE
How to use DETR for a purely classification problem

### ISSUE THREAD

**Issue by WkEEn** [facebookresearch/detr#328]
## ❓ How to do something using DETR

i just want to classify a dataset which contains 5 classes.
However, the datastructure——misc.NestedTensor is just for detection, because "mask" is needed.
I would very much appreciate any help on this!

**Comment by zhiqwang** [comment]
Hi @WkEEn

If you are interested on classification problem, why don't you try [`deit`](https://github.com/facebookresearch/deit)? It's also a *transformer*-based structure and it seems that it's also produced by FAIR teams.

**Comment by alcinos** [comment]
DETR is a detection model, it doesn't really makes sense to use it for classification, unless, maybe, you want to do multi-class classification (I haven't tried myself, but it should be doable).
As @zhiqwang pointed out, there are other models out there that are better suited for this.
I believe I have answered your question and as such I'm closing this. Feel free to reach out if you have further concerns.

**Comment by daimakram** [comment]
Hi @alcinos @zhiqwang 
I was get classification accuracies for validation images. However, I saw the code is using cocoeval.summaize() and cocoeval.accumulate() functions. It only displays mAP and mAR. I also want classification accuracy, precision and recall. Any ideas, on how to add these metrics in evaluation?
