### ISSUE TITLE
inference one image 

### ISSUE THREAD

**Issue by XiaoJiNu** [facebookresearch/detr#33]
hi, how to inference one image with detr?

**Comment by fmassa** [comment]
Hi,

This colab notebook illustrates how to use a demo version of DETR to do inference https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_demo.ipynb
You can also replace the demo DETR model with the torchhub ones (which gives better results).

Some more resources for using DETR for inference on a single image:
- Video explanation https://www.youtube.com/watch?v=LfUsGv-ESbc
- Webdemo https://dash-gallery.plotly.host/dash-detr/ 
  - Code available at https://github.com/fmassa/dash-detr

I believe I've answered your question, so I'm closing the issue, but let us know if you have further questions.
