### ISSUE TITLE
 element in the input with no (zero) ground truth bounding boxes

### ISSUE THREAD

**Issue by hariSky** [facebookresearch/detr#335]
Hi @alcinos 

I am trying to train DETR with some of my inputs being images with no ground truth bounding boxes.
I found a relevant question that has been already answered in the thread here,
https://github.com/facebookresearch/detr/issues/9

However I don't see how the no ground  inputs should be.
I mean, what tensors should I use as targets to the model for label and box(es) if the input is an image with no ground truth bounding boxes? Should it have "nan" value? is there a specific encoding?

Thank you,
Haris

**Comment by alcinos** [comment]
Hello,

I encourage you to read some guides in how to create annotations in COCO format (eg https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch) If the json doesn't contain any annotation referring to a particular image, it is assumed that this image doesn't contain any ground truth box, and DETR will be trained as such.

In code, it means that this vector:
https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/datasets/coco.py#L64
will be empty.

I believe I have answered your question and as such I'm closing this. Feel free to reach out if you have further concerns.

**Comment by aedirn** [comment]
> In code, it means that this vector:
> https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/datasets/coco.py#L64
> 
> 
> will be empty.
> I believe I have answered your question and as such I'm closing this. Feel free to reach out if you have further concerns.

Hi @alcinos, 
Thanks for your answer here. I just want to confirm, the shape of an empty `boxes` should be `[0,4]`, correct?
