### ISSUE TITLE
how to debug in vscode

### ISSUE THREAD

**Issue by seyeeet** [facebookresearch/detr#343]
this is kinda not detr problem, but I guess it is related.
so im using detr and vscode, I want to go through each step of the code to understand what is happening.
when I run in terminal I run `python -m torch.distributed.launch  --nproc_per_node=1 --use_env main.py --coco_path /scratch/shared/MSCOCO/` and it works good.
now i wanna run it in debug mode
so in my vscode in the `launch.json` I added the arguments, something like this
```
{

    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "args":["--coco_path","/scratch/shared/MSCOCO/"]

        }
    ]
}
```
the issue is that I am not sure how to provide `torch.distributed.launch  --nproc_per_node=1 --use_env` for debuging case, where should I put them?
if i add it to args like `"args":["torch.distributed.launch","--nproc_per_node","1","--use_env","--coco_path","/scratch/shared/MSCOCO/"]`
it gives me error.
can someone please help me

**Comment by alcinos** [comment]
Hi @seyeeet 

If you are debugging locally on a single node, you can skip the distributed launch entirely and just use `python main.py`. This should be much easier to debug. Additionally, you may want to set the number of data-loading thread to 0 with `--num_workers 0` to avoid forking and get better backtraces if the issue occurs during dataloading. 

I believe I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
