### ISSUE TITLE
Prediction result is not so good

### ISSUE THREAD

**Issue by wwdok** [facebookresearch/detr#345]
Hi, DETR team, i am attracted by your work that incorporates transformer with CV, then i use the provided colab notebook to play with it, but from the result, i think it is not so good, i am not familiar with transformer so i have no idea why it is such result, i just come to feedback ~ 

![image](https://user-images.githubusercontent.com/43233772/110281620-0a946580-8018-11eb-91d4-4b123419e9df.png)

This image's URL is `https://img.imgdb.cn/item/6045bd27cef1ec5e6f514841.jpg`

**Comment by fmassa** [comment]
Hi,

I tried to run the baseline colab in your image, but I wasn't able to get the image 
![image](https://user-images.githubusercontent.com/9110200/110305999-9baa1300-7ffd-11eb-9c54-5307ece93c0e.png)

Additionally, I would recommend using the notebook from https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb, which uses the models we report in the paper (and not the demo model)

**Comment by wwdok** [comment]
I reuploaded it at another image hosting platform : https://drive.google.com/file/d/1X8fC8ZtlH_S7WQVE6jSeXL7jr4oQPDYD/view?usp=sharing.
I previously used `detr_demo.ipynb` that produce above result, as you suggested, i tried `detr_attention.ipynb`, this time it looks really normal !
<img width="971" alt="下载" src="https://user-images.githubusercontent.com/43233772/110487672-c3e26080-8128-11eb-96e1-7090395ee6ba.png">
