### ISSUE TITLE
Visualization in Fig. 6

### ISSUE THREAD

**Issue by charlesCXK** [facebookresearch/detr#349]
## How to visualize the attention map like Fig. 6 in the main paper?

Hi, thanks for sharing the great work~
I am trying to visualize the attention maps in DETR like Fig.6 in the main paper, but I have no idea how to combine the attention maps with the raw image in that way. I have known how to plot the attention maps like Fig. 3. Could you please give me some advice about Fig. 6? Thank you very much!

**Comment by szagoruyko** [comment]
We took and modified the code from Visualizer class in detectron2 https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/visualizer.py

**Comment by charlesCXK** [comment]
Thanks~

**Comment by GWwangshuo** [comment]
> We took and modified the code from Visualizer class in detectron2 https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/visualizer.py

Could you please kindly provide the modified version of `visualizer.py` fot visualizing attention map in Fig. 6. Thanks a lot.

**Comment by GWwangshuo** [comment]
> We took and modified the code from Visualizer class in detectron2 https://github.com/facebookresearch/detectron2/blob/master/detectron2/utils/visualizer.py

@szagoruyko 
Could you please kindly provide the modified  `visualizer.py`? That will be greatly helpful. Thanks a lot.

**Comment by htyjers** [comment]
> ## How to visualize the attention map like Fig. 6 in the main paper?
> Hi, thanks for sharing the great work~ I am trying to visualize the attention maps in DETR like Fig.6 in the main paper, but I have no idea how to combine the attention maps with the raw image in that way. I have known how to plot the attention maps like Fig. 3. Could you please give me some advice about Fig. 6? Thank you very much!

could you help me to plot the attention maps like Fig3, I have no idea how to realize that, thank you very much
