### ISSUE TITLE
Unable to evaluate model

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/detr#35]
Environment
pytorch 1.3.1
torchvision 0.4.2

I am able to train the model successfully. However, the following mistake appear when I run the evaluation independetly. 

srun --gres gpu:1 python main.py --batch_size 2 --no_aux_loss --eval --resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth --coco_path ../../dataset/

Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/mnt/lustre/chenyuntao1/homes/gaopeng/mask_detr/detr/util/misc.py", line 416, in init_distributed_mode
    world_size=args.world_size, rank=args.rank)
  File "/mnt/lustre/chenyuntao1/homes/gaopeng/anaconda3/envs/detr/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/mnt/lustre/chenyuntao1/homes/gaopeng/anaconda3/envs/detr/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 130, in _env_rendezvous_handler
    raise _env_error("MASTER_ADDR")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set

**Comment by alcinos** [comment]
Hi @gaopengcuhk 
If you are going to use slurm, we recommend using Submitit.
To run your eval on one node, one gpu, you can run
 ```python run_with_submitit.py --ngpus 1 --nodes 1 --timeout 360 --batch_size 2 --no_aux_loss --eval --resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth --coco_path ../../dataset/```

As a side note, your version of pytorch is a bit old, we recommend using pytorch 1.5.

**Comment by gaopengcuhk** [comment]
Thank you very much. I need to modify part of the code to run detr with pytorch 1.3. I will switch to pytorch 1.5 latter.

Thank you very much for your quick response.

**Comment by gaopengcuhk** [comment]
python run_with_submitit.py --ngpus 1 --nodes 1 --timeout 360 --batch_size 2 --no_aux_loss --eval --resume  ./saved_model/detr-r50-e632da11.pth --coco_path ../../dataset/

When I run your code, I run into the following error.

submitit INFO (2020-06-02 21:34:32,188) - Starting with JobEnvironment(job_id=587603, hostname=SH-IDC1-10-198-6-145, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2020-06-02 21:34:32,188) - Loading pickle: experiments/587603/587603_submitted.pkl
Process group: 1 tasks, rank: 0
submitit ERROR (2020-06-02 21:35:20,838) - Submitted job triggered an exception
~

**Comment by fmassa** [comment]
@gaopengcuhk can you paste which exception you got? As this might be an issue with submitit, and not with DETR

**Comment by linzzzzzz** [comment]
I came across similar issue and end up using the command below:

python -m torch.distributed.launch --nproc_per_node=1 --use_env main.py --batch_size 2 --no_aux_loss --eval \
    --resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth \
    --coco_path /path/to/coco

**Comment by alcinos** [comment]
@linzzzzzz You're only using one process, so you can remove the distributed launch entirely:
```
python main.py --batch_size 2 --no_aux_loss --eval
--resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth
--coco_path /path/to/coco
```

**Comment by GlennCGL** [comment]
> python run_with_submitit.py --ngpus 1 --nodes 1 --timeout 360 --batch_size 2 --no_aux_loss --eval --resume ./saved_model/detr-r50-e632da11.pth --coco_path ../../dataset/
> 
> When I run your code, I run into the following error.
> 
> submitit INFO (2020-06-02 21:34:32,188) - Starting with JobEnvironment(job_id=587603, hostname=SH-IDC1-10-198-6-145, local_rank=0(1), node=0(1), global_rank=0(1))
> submitit INFO (2020-06-02 21:34:32,188) - Loading pickle: experiments/587603/587603_submitted.pkl
> Process group: 1 tasks, rank: 0
> submitit ERROR (2020-06-02 21:35:20,838) - Submitted job triggered an exception
> ~

Hi , i am using on 1984 and get the same problems. Could you tell me the solution?
