### ISSUE TITLE
How to train MNIST handwritten digits dataset on this network?

### ISSUE THREAD

**Issue by Vaibhav-ML** [facebookresearch/detr#363]
Hi,

   I want to feed the MNIST handwritten dataset into this network to do some attention visualization.

How can I do this?

**Comment by alcinos** [comment]
Hi @Vaibhav-ML 

There are plenty of resources for training on custom dataset (eg #14 ) as well as a [notebook](https://colab.research.google.com/github/facebookresearch/detr/blob/colab/notebooks/detr_attention.ipynb) to showcase attention visualization. 

I invite you to go through these resources and if something remain unclear, feel free to open an issue with a more pointed questions.
