### ISSUE TITLE
How to detect with my datasets?

### ISSUE THREAD

**Issue by Howdy-Personally** [facebookresearch/detr#366]
## ❓ How to do something using DETR
I wanna detect my datasets, I got latest.pth and I dont know how to eval it.
the model is train with instance .
waiting for your reply.
I'm a fresh man.
Thanks first!

**Comment by NielsRogge** [comment]
See #9, there's an extensive discussion there on how to fine-tune DETR (or train from scratch, if you have at least 10K images) on your custom dataset.

**Comment by alcinos** [comment]
Hi @Howdy-Personally 

Please have a look at the resources available (the notebooks, and some issues as pointed by @NielsRogge).
If something remain unclear, feel free to open an issue with a more pointed question.
