### ISSUE TITLE
how to get the test result like json file?

### ISSUE THREAD

**Issue by zhaiyukun** [facebookresearch/detr#369]
## ❓ How to do something using DETR

how do  I  get the test result in coco format?

**Comment by NielsRogge** [comment]
You can turn the outputs of DETR into COCO format using the [PostProcessor](https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/models/detr.py#L258). As you can see [here](https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/engine.py#L108), this post processor converts the output of DETR to the COCO api, which can then be provided to the `CocoEvaluator` (which can be used to compute metrics like mAP). 

DETR outputs bounding boxes in `(center_x, center_y, width, height)` format, but the COCO format is `(x_1, x_2, y_1, y_2)`. Also, DETR outputs bounding boxes which have to be rescaled to the original size of the image. The post processor takes care of both things.

**Comment by zhaiyukun** [comment]
thanks a lot, I  get it
