### ISSUE TITLE
How to get the inference time (speed) ?

### ISSUE THREAD

**Issue by ilem777** [facebookresearch/detr#370]
## ❓ How to get the inference time or speed using DETR?

I want to make some comparisons between some models, how can I export (print) the inference time when testing or evaling DETR?

**Comment by alcinos** [comment]
Hi @ilem777 
Please see #110 
I'm closing this as it's likely a duplicate. Feel free to reach out if you have further concerns.

**Comment by ilem777** [comment]
@alcinos thank you.

**Comment by ilem777** [comment]
@alcinos Hello, how can I run the "computer_flops.py" file?
I changed PATH_TO_COCO in line 52 to my custom dataset path.
Then I run it, why does it automatically download a model to test it?
I think I should change lines 59~63
```
device = torch.device('cuda')
results = {}
for model_name in ['detr_resnet50']:
    model = torch.hub.load('facebookresearch/detr', model_name, pretrained=True)
    model.to(device)
````
How can I modify these lines to read my trained model? The path of my trained model is in "outputs/checkpint.pth". Thank you, this is really bothering me.

Also I would like to ask how to run the "util/plot_utils.py" file? I don't see any tutorials on the discussion forum, how can I run it? Also, the "log.txt" file is in the "outputs" folder. Thank you very much.
