### ISSUE TITLE
What file does "files" in def plot_precision_recall(files, naming_scheme='iter') refer to and which file do I need?

### ISSUE THREAD

**Issue by ilem777** [facebookresearch/detr#371]
## ❓ How to do something using DETR

Hello, I see that [plot_utils.py](https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/util/plot_utils.py) can plot PR curves, but it requires a "files", what does this "files" refer to?
https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/util/plot_utils.py#L76
Is it "`./outputs/log.txt`" file?
Or is it any of the "`./outputs/checkpoint.pth`"?
Or should I need the "`./outputs`" folder?

Thank you.

**Comment by ilem777** [comment]
I'm really sorry, I've re-edited the question description, can someone please answer it?

**Comment by SeaRealE** [comment]
I solved it with the code below.

```python
from pathlib import Path
files = list(Path('./save/eval').glob('*.pth'))

plot_precision_recall(files)
```

**Comment by SeaRealE** [comment]
I solved it with the code below.

```python
from pathlib import Path

files = list(Path('./outputs/eval').glob('*.pth'))
plot_precision_recall(files)
```

**Comment by ilem777** [comment]
Successfully run, very well, thank you, my friend. @SeaRealE 
![PR_curve](https://user-images.githubusercontent.com/61718945/118590835-cd95dd80-b7d5-11eb-80de-11bc53d5d064.png)

**Comment by 131413ljk** [comment]
Is this "pth" file a pre-trained DETR model?

**Comment by 131413ljk** [comment]
Hello, what do 000,050 and 100 in the picture below mean respectively?

**Comment by seareale** [comment]
@131413ljk Maybe epoch, too old to remember.
