### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by xiyufeng2** [facebookresearch/detr#374]
where can I find the inference demo? thank you!

**Comment by DanielFennhagen** [comment]
You can find a few in the readme: https://github.com/facebookresearch/detr#notebooks

**Comment by xiyufeng2** [comment]
I have checked in the readme:&nbsp;https://github.com/facebookresearch/detr#notebooks
There's no illustration about visualization but only train and eval.
I jest want to test one single picture and visualize.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/detr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/detr] visualization (#374)





 
You can find a few in the readme: https://github.com/facebookresearch/detr#notebooks
