### ISSUE TITLE
Question: how to make Detr work with dynamic input size?

### ISSUE THREAD

**Issue by pfeatherstone** [facebookresearch/detr#388]
## ❓ How to do something using DETR

I would like to use Detr with inputs of arbitrary size. Like, can I train Detr at 512x512, then infer at 1024*78 for example?
Is this possible?

**Comment by fmassa** [comment]
Hi,

Yes, this is possible, and in fact we don't fix the sizes of the inputs during training / inference and they can be different.

I believe I've answered your question and as such I'm closing this issue, but let us know if you have further questions

**Comment by pfeatherstone** [comment]
So looking at the demo model, you use the following:
```
H, W = h.shape[-2:]
  pos = torch.cat([
      self.col_embed[:W].unsqueeze(0).repeat(H, 1, 1),
      self.row_embed[:H].unsqueeze(1).repeat(1, W, 1),
  ], dim=-1).flatten(0, 1).unsqueeze(1)
```

So it looks like value for H, W are bounded. 
You use 
```
self.row_embed = nn.Parameter(torch.rand(50, hidden_dim // 2))
self.col_embed = nn.Parameter(torch.rand(50, hidden_dim // 2))
```

So after the image has passed through the backbone, ```H``` and ```W``` and bounded to 50

**Comment by pfeatherstone** [comment]
So image dimensions are bounded from above by ```[H,W] = [2^4*50, 2^4*50] = [800,800]```.
Is that correct? So Detr can't infer anything bigger than [800,800]?

**Comment by pfeatherstone** [comment]
In which case, strictly speaking, it doesn't fully support dynamic size? @fmassa

**Comment by pfeatherstone** [comment]
@fmassa Can you confirm this?
