### ISSUE TITLE
MAP= -1 and recall = -1 

### ISSUE THREAD

**Issue by woshichunge12** [facebookresearch/detr#389]
Averaged stats: class_error: 0.00  loss: 40.1147 (40.0733)  loss_ce: 0.3519 (0.3519)  loss_bbox: 2.1102 (2.3046)  loss_giou: 3.6782 (3.7595)  loss_ce_0: 0.3752 (0.3752)  loss_bbox_0: 2.2117 (2.3568)  loss_giou_0: 3.8800 (3.8642)  loss_ce_1: 0.3669 (0.3669)  loss_bbox_1: 2.1854 (3.0761)  loss_giou_1: 3.8150 (3.8684)  loss_ce_2: 0.3516 (0.3516)  loss_bbox_2: 2.4525 (2.5718)  loss_giou_2: 3.7798 (3.8288)  loss_ce_3: 0.3543 (0.3543)  loss_bbox_3: 2.0263 (2.4637)  loss_giou_3: 3.8995 (3.9023)  loss_ce_4: 0.3516 (0.3516)  loss_bbox_4: 1.8820 (2.3077)  loss_giou_4: 3.4424 (3.6177)  loss_ce_unscaled: 0.3519 (0.3519)  class_error_unscaled: 0.0000 (0.0000)  loss_bbox_unscaled: 0.4220 (0.4609)  loss_giou_unscaled: 1.8391 (1.8798)  cardinality_error_unscaled: 1.0000 (1.0000)  loss_ce_0_unscaled: 0.3752 (0.3752)  loss_bbox_0_unscaled: 0.4423 (0.4714)  loss_giou_0_unscaled: 1.9400 (1.9321)  cardinality_error_0_unscaled: 1.0000 (1.0000)  loss_ce_1_unscaled: 0.3669 (0.3669)  loss_bbox_1_unscaled: 0.4371 (0.6152)  loss_giou_1_unscaled: 1.9075 (1.9342)  cardinality_error_1_unscaled: 1.0000 (1.0000)  loss_ce_2_unscaled: 0.3516 (0.3516)  loss_bbox_2_unscaled: 0.4905 (0.5144)  loss_giou_2_unscaled: 1.8899 (1.9144)  cardinality_error_2_unscaled: 1.0000 (1.0000)  loss_ce_3_unscaled: 0.3543 (0.3543)  loss_bbox_3_unscaled: 0.4053 (0.4927)  loss_giou_3_unscaled: 1.9497 (1.9511)  cardinality_error_3_unscaled: 1.0000 (1.0000)  loss_ce_4_unscaled: 0.3516 (0.3516)  loss_bbox_4_unscaled: 0.3764 (0.4615)  loss_giou_4_unscaled: 1.7212 (1.8088)  cardinality_error_4_unscaled: 1.0000 (1.0000)
Accumulating evaluation results...
DONE (t=0.01s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

**it looked normal at the beginning of training，There is only one class in my data set，and  i set num_classes =1 in detr,at the same time ,i set my categories_id =0 in my json.**

**Here is my json：**
{
 "info": "spytensor created",
 "license": [
  "license"
 ],
 "images": [
  {
   "height": 2056,
   "width": 2464,
   "id": 0,
   "file_name": "5.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 1,
   "file_name": "178.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 2,
   "file_name": "74.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 3,
   "file_name": "23.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 4,
   "file_name": "204.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 5,
   "file_name": "214.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 6,
   "file_name": "272.bmp"
  },
  {
   "height": 2056,
   "width": 2464,
   "id": 7,
   "file_name": "162.bmp"
  }
 ],
 "annotations": [
  {
   "id": 0,
   "image_id": 0,
   "category_id": 0,
   "segmentation": [
    [
     186.575893,
     906.941148,
     231.594156,
     970.972276
    ]
   ],
   "bbox": [
    186.575893,
    906.941148,
    45.01826299999999,
    64.03112799999997
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 1,
   "image_id": 1,
   "category_id": 0,
   "segmentation": [
    [
     1242.004058,
     242.618191,
     1271.015828,
     270.631809
    ]
   ],
   "bbox": [
    1242.004058,
    242.618191,
    29.01177000000007,
    28.01361799999998
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 2,
   "image_id": 2,
   "category_id": 0,
   "segmentation": [
    [
     1989.307224,
     1172.070039,
     2012.316558,
     1270.117704
    ]
   ],
   "bbox": [
    1989.307224,
    1172.070039,
    23.00933400000008,
    98.04766500000005
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 3,
   "image_id": 3,
   "category_id": 0,
   "segmentation": [
    [
     1673.153137,
     1398.462162,
     1886.402419,
     1576.364865
    ]
   ],
   "bbox": [
    1673.153137,
    1398.462162,
    213.249282,
    177.90270299999997
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 4,
   "image_id": 4,
   "category_id": 0,
   "segmentation": [
    [
     1809.787016,
     1017.327417,
     1844.600228,
     1056.64746
    ]
   ],
   "bbox": [
    1809.787016,
    1017.327417,
    34.81321200000002,
    39.32004299999994
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 5,
   "image_id": 5,
   "category_id": 0,
   "segmentation": [
    [
     282.614854,
     725.853113,
     305.624188,
     766.873054
    ]
   ],
   "bbox": [
    282.614854,
    725.853113,
    23.009334000000024,
    41.01994100000002
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 6,
   "image_id": 6,
   "category_id": 0,
   "segmentation": [
    [
     1853.252029,
     939.957198,
     1903.272321,
     1062.016537
    ]
   ],
   "bbox": [
    1853.252029,
    939.957198,
    50.02029199999993,
    122.05933900000002
   ],
   "iscrowd": 0,
   "area": 1.0
  },
  {
   "id": 7,
   "image_id": 7,
   "category_id": 0,
   "segmentation": [
    [
     1350.04789,
     1748.350195,
     1580.141234,
     1908.428016
    ]
   ],
   "bbox": [
    1350.04789,
    1748.350195,
    230.0933439999999,
    160.07782100000009
   ],
   "iscrowd": 0,
   "area": 1.0
  }
 ],
 "categories": [
  {
   "id": 0,
   "name": "person"
  }
 ]
}

**Comment by alcinos** [comment]
You are getting -1 AP for medium and large objects, which means that all the objects in your dataset are small.

You could change the size thresholds in the coco tools to something that makes more sense for your usecase.

I believe I have answered your question, feel free to reach out if you have further concerns.

**Comment by woshichunge12** [comment]
@alcinos 
Thank you very much for your help, does this "size thresholds" refer to the conversion operation in coco.py，for example:
return T.Compose([
            T.RandomHorizontalFlip(),
            T.RandomSelect(
                T.RandomResize(scales, max_size=1333),
                T.Compose([
                    T.RandomResize([400, 500, 600]),
                    T.RandomSizeCrop(384, 600),
                    T.RandomResize(scales, max_size=1333),
                ])
            ),
            normalize,
        ])

**Comment by alcinos** [comment]
No, they are defined by the coco tools: https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L509-L510
Apparently, all your objects have an area smaller than 32**2

**Comment by woshichunge12** [comment]
@alcinos 
yes，you are right，the size of the objects in my image is really small，but this method does not work

**Comment by woshichunge12** [comment]
@alcinos 
yes，you are right，the size of the objects in my image is really small，but this method does not work
