### ISSUE TITLE
why L_Hungarian and L_match inconsistent

### ISSUE THREAD

**Issue by ltm920716** [facebookresearch/detr#390]
hello，
    The forms of  classification loss part are inconsistent between L_Hungarian（cross entropy） and  L_match（-p）. I do not know if it will get better performance when they are consistent，thanks

**Comment by alcinos** [comment]
This is explained in our paper, in the loss section.
"In the matching cost we use probabilities  ˆpˆσ(i)(ci) instead of log-probabilities. This makes the class prediction term commensurable to Lbox(·,·) (described below), and we observed better empirical performances."
