### ISSUE TITLE
Code error if float (torchvision .__ version __ [: 3]) <0.7: using torchvision> = 0.10.0 in misc.py

### ISSUE THREAD

**Issue by ruben1961** [facebookresearch/detr#401]
Hello dears

I think there is an error in the encoding of line 23 of the file detr/util/misc.py, it says 'if float (torchvision .__ version __ [: 3]) <0.7', in the documentation requirements.txt indicates that it is you can use torchvision> = 0.6.0, if I have torchvision version == 0.10.0 the response from float (torchvision .__ version __ [: 3]) gives a value of 0.1, which is True and causes an error.

I had to modify the code for it to work. Thanks.

**Comment by szagoruyko** [comment]
fixed by #404
