### ISSUE TITLE
torchvision 0.10.0 support

### ISSUE THREAD

**Issue by HoBeom** [facebookresearch/detr#403]
https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/util/misc.py#L21

if torchvision.__version__ == 0.10.0
torchvision.__version__[:3] -> 0.1

replace code Line 21
`
if float(torchvision.__version__.split(".")[1]) < 7.0:
`

and Line 457
`
    if float(torchvision.__version__.split(".")[1]) < 7.0:
`

**Comment by HoBeom** [comment]
please check PR #404 :smile:

**Comment by fmassa** [comment]
Thanks for fixing it!
