### ISSUE TITLE
Some confusion about HungarianMatcher

### ISSUE THREAD

**Issue by zymale** [facebookresearch/detr#407]
in the file matcher.py line 68 and line 74:
 line 68:  cost_class=-out_prob[:,tgt_ids]
If don’t do squaring later in line 77, there is no problem with 1-omit here. If  do squaring and 1-omit, in order to obtain the smallest match, category probability becoming close to 0, instead of close to  1,which is GT. The same problem as line 74

**Comment by ghy0324** [comment]
line 77 is actually not performing squaring. `self.cost_class`  is just a coefficient.

**Comment by zymale** [comment]
Yes, you are right. Because the name is a little similar, I read it wrong. Your reply has solved my doubts. Thank you.
