### ISSUE TITLE
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' 

### ISSUE THREAD

**Issue by wuwuwuyu** [facebookresearch/detr#417]
using
python main.py --dataset_file "coco" --coco_path data/coco --epochs 100 --lr=1e-4 --batch_size=2 --num_workers=4 --output_dir="outputs" --resume="detr-r50_3.pth"
happen
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops'

**Comment by fmassa** [comment]
Hi,

This should have been fixed with https://github.com/facebookresearch/detr/pull/404

Let us know if using latest master doesn't work for you.
