### ISSUE TITLE
panoptic segmentation visualization

### ISSUE THREAD

**Issue by shidilrzf** [facebookresearch/detr#50]
Very nice repo!

I want to do a simple inference with the panoptic segmentation model. How can I visualize the output of the panoptic model after the "panoptic post-processing"? 

Thanks ;)

**Comment by alcinos** [comment]
Hello,
Thanks for your interest in DETR. There is already an issue tracking panoptic visualization status: #20  
We are expecting to release it soon.
I'm closing this issue, feel free to comment in the other one.
