### ISSUE TITLE
Can you share the training log for 300 epoches?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/detr#57]
Thank you so much for sharing the log for 150 epochs.

Can you share 300 epochs?

**Comment by fmassa** [comment]
Thanks for opening the issue!

We will be sharing the training logs for all torchhub models early next week.

**Comment by gaopengcuhk** [comment]
Do you have any update?

**Comment by fmassa** [comment]
Hi @gaopengcuhk 

Sorry for the delay.

The logs for the pre-trained models in torchhub (trained over 500 epochs) have been added in https://github.com/facebookresearch/detr/pull/86 (for now only detection).

Let us know if you have further questions.
