### ISSUE TITLE
use plot_logs function from plot_utils -  errors if you only have a single log.txt?

### ISSUE THREAD

**Issue by lessw2020** [facebookresearch/detr#58]
## ❓ How to do something using DETR

Describe what you want to do, including:
1. what inputs you will provide, if any:
log files from training
2. what outputs you are expecting:
plots of the various losses

I'm trying to make use of the plot_logs function in /util/plot_utils.py
In Jupyter, I'm passing a Pathlib  to the dir with my log.txt...but that immediately generates a TypeError: 'PosixPath' object is not iterable...which makes sense, I'm just passing in the dir of the single log.txt, so nothing to iterate.
I changed the code to not iterate and just read the single file into a df and ultimately got the graphs to print...but clearly I'm not calling it correctly?
Is there a preferred way to call/plot a single log file without removing all the list comprehensions?

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detr/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to DETR, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by shidilrzf** [comment]
@lessw2020 I think you should pass it as a list of directories. If you have only one output folder put it in a list

**Comment by lessw2020** [comment]
Hi @shidilrzf  - you are right.  They are expecting an actual list of directories...vs I was thinking in terms of posix path.

I  updated the function to put it in a list so I don't have to do that every time I use it :) 
`
if not isinstance(logs, list):
        logs = [logs]
        print(f"adjusted to list...")
`
Thanks much for pointing it out!

**Comment by fmassa** [comment]
Hi,

@shidilrzf is correct: we expect a list of directories because we used it mostly to compare between different experiments.

We would accept PRs making it auto-wrap into a list if it isn't already, so if you would like to send a PR it would be nice.

Given that this isn't a bug per se, I'm closing the issue but let us know if you have further questions.

**Comment by eslambakr** [comment]
Hello, 
I am facing this error while using it 
"ValueError: Unexpected character found when decoding 'NaN'"

Here u are how I call it:
`p = Path("/bla/bla/log/");
plot_logs(p, fields=('loss', 'class_error', 'loss_bbox_unscaled', 'mAP'), ewm_col=0, log_name='log.txt')`
