### ISSUE TITLE
What is mean of self[0] and self[1] in Joiner class?

### ISSUE THREAD

**Issue by LiangHann** [facebookresearch/detr#71]
class Joiner(nn.Sequential):
    def __init__(self, backbone, position_embedding):
        super().__init__(backbone, position_embedding)

    def forward(self, tensor_list):
        xs = self[0](tensor_list)
        out = []
        pos = []
        for name, x in xs.items():
            out.append(x)
            # position encoding
            pos.append(self[1](x).to(x.tensors.dtype))

        return out, pos

What is the meaning of self[0] and self[1] here?

Many thanks.

**Comment by alcinos** [comment]
Hi,
As you can see the `Joiner` class inherits from `nn.Sequential`. As a result is shares its API, in particular the access of the different layers as a list.
Given the way it's initialized, we thus conclude that:

- `self[0]` is `backbone`
- `self[1]` is `position_embedding`

I believe I have answered your question and as such I'm closing this. If you have further concerns, feel free to reach out.
