### ISSUE TITLE
Do you report performance about instance segmentation?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/detr#74]
## ❓ How to do something using DETR

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detr/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to DETR, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by gaopengcuhk** [comment]
As the name implies, have you ever conduct any experiments on Mask RCNN?

**Comment by alcinos** [comment]
Hi @gaopengcuhk 
We haven't specifically explored instance segmentation. We report some AP numbers in last column of table 5 (trained on coco panoptic), but this is indicative only and we did not focus on that.

I think I have answered your question, and as such I'm closing this issue. If you have further questions, please reach out.
