### ISSUE TITLE
What does it take to add instance segmentation support?

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detr#79]
What does it take to add instance segmentation support?  Any guidance appreciated.

**Comment by alcinos** [comment]
Hi @jackkwok 
Instance segmentation is already mostly there, since it's a subset of panoptic segmentation.
What do you need exactly?

**Comment by jackkwok** [comment]
@alcinos : Unlike instance segmentation, each pixel in panoptic segmentation has only one label corresponding to instance i.e. there are no overlapping instances.  I need to support overlapping instances.

**Comment by alcinos** [comment]
The non-overlapping property is enforced only in the panoptic post-processing (that you can entirely avoid if you don't want it), not in the loss at all. If you provide overlapping masks in your training, DETR will learn to output overlapping masks.

**Comment by jackkwok** [comment]
@alcinos: that's great because it's exactly what I need.  Thank you for clarifying.
