### ISSUE TITLE
Can I use this model with libtorch in C++

### ISSUE THREAD

**Issue by Ncurls** [facebookresearch/detr#81]
I want to use this model in C++.
My inputs is video and I want to do Panoramic segmentation on it.
My expected output is Segmented image

**Comment by fmassa** [comment]
Hi,

We have added torchscript support for the basic DETR model (for boxes), so it can be exported to libtorch in C++, see https://github.com/facebookresearch/detr/pull/51

We didn't do it for panoptic segmentation yet, but I would expect it to be fairly similar, and PRs adding support for it are welcome!

**Comment by fmassa** [comment]
Hi,

TorchScript support for panoptic segmentation models should be added with https://github.com/facebookresearch/detr/pull/87 , so you should be able to use it in libtorch from C++ once the PR gets merged.
