### ISSUE TITLE
Training with Negatives

### ISSUE THREAD

**Issue by kbiyani33** [facebookresearch/detr#82]
## ❓ How to do something using DETR

I want to train a text box detector. My annotations are in COCO Format. I wish to train my textbox detector with some training negatives so that I can ensure that no bounding boxes are predicted in the inputs that are similar to the negatives. 

Any idea as to how do we annotate images with no targets or no bounding boxes?
I mean do I give the annotations as [0,0,0,0] for each class or [None, None, None, None]. 

Or do I leave them completely leave it empty in the ["annotations"] key of COCO format and just add the filenames to ["images"] to the list?

**Comment by fmassa** [comment]
Hi,

All you need to do is to return a empty box, of shape `[0, 4]` in your dataset, as well as an empty label.
Here is an example that you should do in your dataset
```python
boxes = torch.empty((0, 4), dtype=torch.float32)
labels = torch.empty((0,), dtype=torch.int64)
```
and similarly for iscrowd, areas etc.

I believe I have answered your question, and as such I'm closing the issue, but let us know if you have further questions.
