### ISSUE TITLE
ablation study of intermediate supervision

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/detr#85]
Can you share the influence of intermediate supervision on the final performance for DETR?

**Comment by fmassa** [comment]
Hi,

The numbers I have are with an older version of the code, so I'm re-running this ablation with latest implementation and will update the issue once I get the results.

**Comment by fmassa** [comment]
Hi,

I've re-run the ablations using `--no_aux_loss` to compare against the baseline.

Without using auxiliary classifiers, the mAP after 300 epochs is only 35.5, compared to 40.8 if you use auxiliary classifiers.
- Orange: baseline
- Blue: `--no_aux_loss`
![image](https://user-images.githubusercontent.com/9110200/85270272-58ad0d00-b479-11ea-87e5-c1ece31f696e.png)
which, if we compare to Fig 4 in the paper, shows that without auxiliary losses, adding more than 1 decoder layer seems to bring marginal gains.

I believe I've answered your question, and as such I'm closing this issue, but let us know if you have further questions.

**Comment by PkuRainBow** [comment]
@fmassa Great explanation!  I am wondering about the loss weights on the supervision over intermediate predictions.  It would be great if could share with me how does the choice of the loss weights influence the final performance.
