### ISSUE TITLE
Save model from local training

### ISSUE THREAD

**Issue by EmmanouelP** [facebookresearch/detr#92]
Hello and thank you for your amazing work on DETR. 
I am using the guidelines to train on coco dataset but when I finish training I can not see where the model is saved locally. Shouldn't there be a .pth file saved on my machine or am I getting something wrong here? Thanks in advance.

**Comment by EmmanouelP** [comment]
Nevermind i worked it out.

**Comment by LiangHann** [comment]
@EmmanouelP where is the model saved?

**Comment by EmmanouelP** [comment]
You have to add the --output_dir argument in your command, e.g. python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --coco_path /path/to/coco --output_dir /path/to/save/

**Comment by fmassa** [comment]
I believe this can be a recurring issue, so if you would like to send a PR improving the README we would happily accept it
