### ISSUE TITLE
Pre-norm or Post-norm

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/detr#93]
In your code, it seems that you are using pre-norm. While in figure 10 in your paper, you are using post-norm. Can you provide any ablation study on pre-norm and post-norm?

**Comment by alcinos** [comment]
The code is also using post-norm by default, unless you supply `--pre-norm`. We don't have a rigorous ablation of the difference, but initial experiments were suggesting it was slightly worse, so we stuck to the vanilla transformer (ie post-norm)

Feel free to run and report your results if it is important to you.
I believe that I have answered your question, and as such I'm closing this. Feel free to reach out if you have further concerns.
