### ISSUE TITLE
Question about the normalization layer in the Decoder of the Transformer

### ISSUE THREAD

**Issue by wsnedy** [facebookresearch/detr#94]
Hi, 
First of all, thanks for the great repo. 

The output of the `TransformerDecoderLayer`  is [normalized](https://github.com/facebookresearch/detr/blob/master/models/transformer.py#L232) as the parameter `normalize_before` is set as `False`. Why do we need to normalize the output of `TransformerDecoder` again in [line113](https://github.com/facebookresearch/detr/blob/master/models/transformer.py#L113) and [line116](https://github.com/facebookresearch/detr/blob/master/models/transformer.py#L116)? (It is always True to pass the `decoder_norm` to the [`TransformerDecoder`](https://github.com/facebookresearch/detr/blob/master/models/transformer.py#L33).)
 Is it intended to do that? Or the `decoder_norm` should be the same as the `encoder_norm`, which depends on the `normalize_before`. Any explanation would be appreciated.

**Comment by chrisway613** [comment]
I‘ve found this question too!
If 'normalize_before' is set as False, it will do duplicated normalization.

**Comment by jackroos** [comment]
Also confused by this duplicated normalization.

**Comment by OwalnutO** [comment]
The transformer is built in transformer.py line 276 with 'normalize_before=args.pre_norm', and in main.py line 57, the 'pre_norm' is default True

**Comment by turboxin** [comment]
[https://github.com/pytorch/pytorch/issues/24930](url) explained that nn.LayerNorm(nn.LayerNorm(x)) is equal to nn.LayerNorm(x), so duplicated normalization is OK.

**Comment by fmassa** [comment]
Hi,

For simplicity, we closely follow the Transformer implementation from PyTorch, so the comment in https://github.com/facebookresearch/detr/issues/94#issuecomment-694203829 is spot on.

**Comment by wsnedy** [comment]
Hi,
Thanks for the response. I got it.
