### ISSUE TITLE
why the lr_transformer and lr_backbone is not the same?

### ISSUE THREAD

**Issue by iFighting** [facebookresearch/detr#95]
why the lr_transformer and lr_backbone is not the same?

if i set lr_transformer = lr_backbone, what will happen?

**Comment by alcinos** [comment]
Hello @iFighting 
The transformer is trained from scratch, while the backbone is fine-tuned, hence the need for different learning rates. Also, intuitively, these architectures are very different, which could also explain the need for different learning rates.

With lr_transformer == lr_backbone, you'll get much lower performance.

I believe I have answered your question, and as such I'm closing this. If you have further concerns, feel free to reach out.
