### ISSUE TITLE
Question about mask variable in transformer

### ISSUE THREAD

**Issue by jianghaoyuan1994** [facebookresearch/detr#96]
Hi, i am confused in mask in transformer.
I see in ```nested_tensor_from_tensor_list``` you create mask with its value is all True. And in ``` TransformerEncoderLayer``` you pass it though  argument key_padding_mask into nn.MultiheadAttention, in pytorch API its say:  When the value is True, the corresponding value on the attention layer will be filled with -inf. So i am very confused why make its attention weight equal 0 in encoder?

**Comment by fmassa** [comment]
Hi,

In https://github.com/facebookresearch/detr/blob/1fcfc65f5cfef0836d349d618aa4afe30aeb838e/util/misc.py#L297
we set the `mask` to `False` for all the elements that are not part of the padding.

I believe I've answered your question, so I'm closing the issue, but let us know if you have further questions.

**Comment by jianghaoyuan1994** [comment]
Thank you~

**Comment by ayberksener** [comment]
@fmassa @jianghaoyuan1994 Hi, I am getting mask = True for my images. My image size are (1152,1152) so is there any way around to make them false, because I think my network is not training because of getting true values in the mask. Kindly help me in this regard.
