### ISSUE TITLE
Have the DETR been trained on default hyperparameters listed in main.py?

### ISSUE THREAD

**Issue by saahiluppal** [facebookresearch/detr#99]
I was wondering if this DETR model have been trained on default hyperparameters listed in https://github.com/facebookresearch/detr/blob/master/main.py. ??

**Comment by fmassa** [comment]
Yes, that's correct.

The ablations have all been trained on 300 epochs on 32 GPUs, while the final results models (present in Table 1 in the paper) have been trained on 500 epochs.

I believe I have answered your question, and as such I'm closing this issue, but please let us know if you have further questions.
